package com.genetech.bean;

import java.math.BigDecimal;

public class Goods {

    public Goods() {
    }

    public Goods(Integer id, BigDecimal price, String name, String attachment_urls, Integer status, String product_code, Integer stock, String goods_code, Integer product_id, String introduction) {
        this.id = id;
        this.price = price;
        this.name = name;
        this.attachment_urls = attachment_urls;
        this.status = status;
        this.product_code = product_code;
        this.stock = stock;
        this.goods_code = goods_code;
        this.product_id = product_id;
        this.introduction = introduction;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.id
     *
     * @mbg.generated Wed Jan 01 22:09:08 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.price
     *
     * @mbg.generated Wed Jan 01 22:09:08 CST 2020
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.name
     *
     * @mbg.generated Wed Jan 01 22:09:08 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.attachment_urls
     *
     * @mbg.generated Wed Jan 01 22:09:08 CST 2020
     */
    private String attachment_urls;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.status
     *
     * @mbg.generated Wed Jan 01 22:09:08 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.product_code
     *
     * @mbg.generated Wed Jan 01 22:09:08 CST 2020
     */
    private String product_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.stock
     *
     * @mbg.generated Wed Jan 01 22:09:08 CST 2020
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.goods_code
     *
     * @mbg.generated Wed Jan 01 22:09:08 CST 2020
     */
    private String goods_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.product_id
     *
     * @mbg.generated Wed Jan 01 22:09:08 CST 2020
     */
    private Integer product_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.introduction
     *
     * @mbg.generated Wed Jan 01 22:09:08 CST 2020
     */
    private String introduction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.id
     *
     * @return the value of t_goods.id
     *
     * @mbg.generated Wed Jan 01 22:09:08 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.id
     *
     * @param id the value for t_goods.id
     *
     * @mbg.generated Wed Jan 01 22:09:08 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.price
     *
     * @return the value of t_goods.price
     *
     * @mbg.generated Wed Jan 01 22:09:08 CST 2020
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.price
     *
     * @param price the value for t_goods.price
     *
     * @mbg.generated Wed Jan 01 22:09:08 CST 2020
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.name
     *
     * @return the value of t_goods.name
     *
     * @mbg.generated Wed Jan 01 22:09:08 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.name
     *
     * @param name the value for t_goods.name
     *
     * @mbg.generated Wed Jan 01 22:09:08 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.attachment_urls
     *
     * @return the value of t_goods.attachment_urls
     *
     * @mbg.generated Wed Jan 01 22:09:08 CST 2020
     */
    public String getAttachment_urls() {
        return attachment_urls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.attachment_urls
     *
     * @param attachment_urls the value for t_goods.attachment_urls
     *
     * @mbg.generated Wed Jan 01 22:09:08 CST 2020
     */
    public void setAttachment_urls(String attachment_urls) {
        this.attachment_urls = attachment_urls == null ? null : attachment_urls.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.status
     *
     * @return the value of t_goods.status
     *
     * @mbg.generated Wed Jan 01 22:09:08 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.status
     *
     * @param status the value for t_goods.status
     *
     * @mbg.generated Wed Jan 01 22:09:08 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.product_code
     *
     * @return the value of t_goods.product_code
     *
     * @mbg.generated Wed Jan 01 22:09:08 CST 2020
     */
    public String getProduct_code() {
        return product_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.product_code
     *
     * @param product_code the value for t_goods.product_code
     *
     * @mbg.generated Wed Jan 01 22:09:08 CST 2020
     */
    public void setProduct_code(String product_code) {
        this.product_code = product_code == null ? null : product_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.stock
     *
     * @return the value of t_goods.stock
     *
     * @mbg.generated Wed Jan 01 22:09:08 CST 2020
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.stock
     *
     * @param stock the value for t_goods.stock
     *
     * @mbg.generated Wed Jan 01 22:09:08 CST 2020
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goods_code
     *
     * @return the value of t_goods.goods_code
     *
     * @mbg.generated Wed Jan 01 22:09:08 CST 2020
     */
    public String getGoods_code() {
        return goods_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goods_code
     *
     * @param goods_code the value for t_goods.goods_code
     *
     * @mbg.generated Wed Jan 01 22:09:08 CST 2020
     */
    public void setGoods_code(String goods_code) {
        this.goods_code = goods_code == null ? null : goods_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.product_id
     *
     * @return the value of t_goods.product_id
     *
     * @mbg.generated Wed Jan 01 22:09:08 CST 2020
     */
    public Integer getProduct_id() {
        return product_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.product_id
     *
     * @param product_id the value for t_goods.product_id
     *
     * @mbg.generated Wed Jan 01 22:09:08 CST 2020
     */
    public void setProduct_id(Integer product_id) {
        this.product_id = product_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.introduction
     *
     * @return the value of t_goods.introduction
     *
     * @mbg.generated Wed Jan 01 22:09:08 CST 2020
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.introduction
     *
     * @param introduction the value for t_goods.introduction
     *
     * @mbg.generated Wed Jan 01 22:09:08 CST 2020
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }
}