package com.genetech.bean;

import java.util.ArrayList;
import java.util.List;

public class InvoiceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_invoice
     *
     * @mbg.generated Wed Dec 18 11:24:48 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_invoice
     *
     * @mbg.generated Wed Dec 18 11:24:48 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_invoice
     *
     * @mbg.generated Wed Dec 18 11:24:48 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invoice
     *
     * @mbg.generated Wed Dec 18 11:24:48 CST 2019
     */
    public InvoiceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invoice
     *
     * @mbg.generated Wed Dec 18 11:24:48 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invoice
     *
     * @mbg.generated Wed Dec 18 11:24:48 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invoice
     *
     * @mbg.generated Wed Dec 18 11:24:48 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invoice
     *
     * @mbg.generated Wed Dec 18 11:24:48 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invoice
     *
     * @mbg.generated Wed Dec 18 11:24:48 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invoice
     *
     * @mbg.generated Wed Dec 18 11:24:48 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invoice
     *
     * @mbg.generated Wed Dec 18 11:24:48 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invoice
     *
     * @mbg.generated Wed Dec 18 11:24:48 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invoice
     *
     * @mbg.generated Wed Dec 18 11:24:48 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invoice
     *
     * @mbg.generated Wed Dec 18 11:24:48 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_invoice
     *
     * @mbg.generated Wed Dec 18 11:24:48 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTaxpayer_numberIsNull() {
            addCriterion("taxpayer_number is null");
            return (Criteria) this;
        }

        public Criteria andTaxpayer_numberIsNotNull() {
            addCriterion("taxpayer_number is not null");
            return (Criteria) this;
        }

        public Criteria andTaxpayer_numberEqualTo(String value) {
            addCriterion("taxpayer_number =", value, "taxpayer_number");
            return (Criteria) this;
        }

        public Criteria andTaxpayer_numberNotEqualTo(String value) {
            addCriterion("taxpayer_number <>", value, "taxpayer_number");
            return (Criteria) this;
        }

        public Criteria andTaxpayer_numberGreaterThan(String value) {
            addCriterion("taxpayer_number >", value, "taxpayer_number");
            return (Criteria) this;
        }

        public Criteria andTaxpayer_numberGreaterThanOrEqualTo(String value) {
            addCriterion("taxpayer_number >=", value, "taxpayer_number");
            return (Criteria) this;
        }

        public Criteria andTaxpayer_numberLessThan(String value) {
            addCriterion("taxpayer_number <", value, "taxpayer_number");
            return (Criteria) this;
        }

        public Criteria andTaxpayer_numberLessThanOrEqualTo(String value) {
            addCriterion("taxpayer_number <=", value, "taxpayer_number");
            return (Criteria) this;
        }

        public Criteria andTaxpayer_numberLike(String value) {
            addCriterion("taxpayer_number like", value, "taxpayer_number");
            return (Criteria) this;
        }

        public Criteria andTaxpayer_numberNotLike(String value) {
            addCriterion("taxpayer_number not like", value, "taxpayer_number");
            return (Criteria) this;
        }

        public Criteria andTaxpayer_numberIn(List<String> values) {
            addCriterion("taxpayer_number in", values, "taxpayer_number");
            return (Criteria) this;
        }

        public Criteria andTaxpayer_numberNotIn(List<String> values) {
            addCriterion("taxpayer_number not in", values, "taxpayer_number");
            return (Criteria) this;
        }

        public Criteria andTaxpayer_numberBetween(String value1, String value2) {
            addCriterion("taxpayer_number between", value1, value2, "taxpayer_number");
            return (Criteria) this;
        }

        public Criteria andTaxpayer_numberNotBetween(String value1, String value2) {
            addCriterion("taxpayer_number not between", value1, value2, "taxpayer_number");
            return (Criteria) this;
        }

        public Criteria andRegist_addressIsNull() {
            addCriterion("regist_address is null");
            return (Criteria) this;
        }

        public Criteria andRegist_addressIsNotNull() {
            addCriterion("regist_address is not null");
            return (Criteria) this;
        }

        public Criteria andRegist_addressEqualTo(String value) {
            addCriterion("regist_address =", value, "regist_address");
            return (Criteria) this;
        }

        public Criteria andRegist_addressNotEqualTo(String value) {
            addCriterion("regist_address <>", value, "regist_address");
            return (Criteria) this;
        }

        public Criteria andRegist_addressGreaterThan(String value) {
            addCriterion("regist_address >", value, "regist_address");
            return (Criteria) this;
        }

        public Criteria andRegist_addressGreaterThanOrEqualTo(String value) {
            addCriterion("regist_address >=", value, "regist_address");
            return (Criteria) this;
        }

        public Criteria andRegist_addressLessThan(String value) {
            addCriterion("regist_address <", value, "regist_address");
            return (Criteria) this;
        }

        public Criteria andRegist_addressLessThanOrEqualTo(String value) {
            addCriterion("regist_address <=", value, "regist_address");
            return (Criteria) this;
        }

        public Criteria andRegist_addressLike(String value) {
            addCriterion("regist_address like", value, "regist_address");
            return (Criteria) this;
        }

        public Criteria andRegist_addressNotLike(String value) {
            addCriterion("regist_address not like", value, "regist_address");
            return (Criteria) this;
        }

        public Criteria andRegist_addressIn(List<String> values) {
            addCriterion("regist_address in", values, "regist_address");
            return (Criteria) this;
        }

        public Criteria andRegist_addressNotIn(List<String> values) {
            addCriterion("regist_address not in", values, "regist_address");
            return (Criteria) this;
        }

        public Criteria andRegist_addressBetween(String value1, String value2) {
            addCriterion("regist_address between", value1, value2, "regist_address");
            return (Criteria) this;
        }

        public Criteria andRegist_addressNotBetween(String value1, String value2) {
            addCriterion("regist_address not between", value1, value2, "regist_address");
            return (Criteria) this;
        }

        public Criteria andRegist_phoneIsNull() {
            addCriterion("regist_phone is null");
            return (Criteria) this;
        }

        public Criteria andRegist_phoneIsNotNull() {
            addCriterion("regist_phone is not null");
            return (Criteria) this;
        }

        public Criteria andRegist_phoneEqualTo(String value) {
            addCriterion("regist_phone =", value, "regist_phone");
            return (Criteria) this;
        }

        public Criteria andRegist_phoneNotEqualTo(String value) {
            addCriterion("regist_phone <>", value, "regist_phone");
            return (Criteria) this;
        }

        public Criteria andRegist_phoneGreaterThan(String value) {
            addCriterion("regist_phone >", value, "regist_phone");
            return (Criteria) this;
        }

        public Criteria andRegist_phoneGreaterThanOrEqualTo(String value) {
            addCriterion("regist_phone >=", value, "regist_phone");
            return (Criteria) this;
        }

        public Criteria andRegist_phoneLessThan(String value) {
            addCriterion("regist_phone <", value, "regist_phone");
            return (Criteria) this;
        }

        public Criteria andRegist_phoneLessThanOrEqualTo(String value) {
            addCriterion("regist_phone <=", value, "regist_phone");
            return (Criteria) this;
        }

        public Criteria andRegist_phoneLike(String value) {
            addCriterion("regist_phone like", value, "regist_phone");
            return (Criteria) this;
        }

        public Criteria andRegist_phoneNotLike(String value) {
            addCriterion("regist_phone not like", value, "regist_phone");
            return (Criteria) this;
        }

        public Criteria andRegist_phoneIn(List<String> values) {
            addCriterion("regist_phone in", values, "regist_phone");
            return (Criteria) this;
        }

        public Criteria andRegist_phoneNotIn(List<String> values) {
            addCriterion("regist_phone not in", values, "regist_phone");
            return (Criteria) this;
        }

        public Criteria andRegist_phoneBetween(String value1, String value2) {
            addCriterion("regist_phone between", value1, value2, "regist_phone");
            return (Criteria) this;
        }

        public Criteria andRegist_phoneNotBetween(String value1, String value2) {
            addCriterion("regist_phone not between", value1, value2, "regist_phone");
            return (Criteria) this;
        }

        public Criteria andOpen_bankIsNull() {
            addCriterion("open_bank is null");
            return (Criteria) this;
        }

        public Criteria andOpen_bankIsNotNull() {
            addCriterion("open_bank is not null");
            return (Criteria) this;
        }

        public Criteria andOpen_bankEqualTo(String value) {
            addCriterion("open_bank =", value, "open_bank");
            return (Criteria) this;
        }

        public Criteria andOpen_bankNotEqualTo(String value) {
            addCriterion("open_bank <>", value, "open_bank");
            return (Criteria) this;
        }

        public Criteria andOpen_bankGreaterThan(String value) {
            addCriterion("open_bank >", value, "open_bank");
            return (Criteria) this;
        }

        public Criteria andOpen_bankGreaterThanOrEqualTo(String value) {
            addCriterion("open_bank >=", value, "open_bank");
            return (Criteria) this;
        }

        public Criteria andOpen_bankLessThan(String value) {
            addCriterion("open_bank <", value, "open_bank");
            return (Criteria) this;
        }

        public Criteria andOpen_bankLessThanOrEqualTo(String value) {
            addCriterion("open_bank <=", value, "open_bank");
            return (Criteria) this;
        }

        public Criteria andOpen_bankLike(String value) {
            addCriterion("open_bank like", value, "open_bank");
            return (Criteria) this;
        }

        public Criteria andOpen_bankNotLike(String value) {
            addCriterion("open_bank not like", value, "open_bank");
            return (Criteria) this;
        }

        public Criteria andOpen_bankIn(List<String> values) {
            addCriterion("open_bank in", values, "open_bank");
            return (Criteria) this;
        }

        public Criteria andOpen_bankNotIn(List<String> values) {
            addCriterion("open_bank not in", values, "open_bank");
            return (Criteria) this;
        }

        public Criteria andOpen_bankBetween(String value1, String value2) {
            addCriterion("open_bank between", value1, value2, "open_bank");
            return (Criteria) this;
        }

        public Criteria andOpen_bankNotBetween(String value1, String value2) {
            addCriterion("open_bank not between", value1, value2, "open_bank");
            return (Criteria) this;
        }

        public Criteria andOpen_accountIsNull() {
            addCriterion("open_account is null");
            return (Criteria) this;
        }

        public Criteria andOpen_accountIsNotNull() {
            addCriterion("open_account is not null");
            return (Criteria) this;
        }

        public Criteria andOpen_accountEqualTo(String value) {
            addCriterion("open_account =", value, "open_account");
            return (Criteria) this;
        }

        public Criteria andOpen_accountNotEqualTo(String value) {
            addCriterion("open_account <>", value, "open_account");
            return (Criteria) this;
        }

        public Criteria andOpen_accountGreaterThan(String value) {
            addCriterion("open_account >", value, "open_account");
            return (Criteria) this;
        }

        public Criteria andOpen_accountGreaterThanOrEqualTo(String value) {
            addCriterion("open_account >=", value, "open_account");
            return (Criteria) this;
        }

        public Criteria andOpen_accountLessThan(String value) {
            addCriterion("open_account <", value, "open_account");
            return (Criteria) this;
        }

        public Criteria andOpen_accountLessThanOrEqualTo(String value) {
            addCriterion("open_account <=", value, "open_account");
            return (Criteria) this;
        }

        public Criteria andOpen_accountLike(String value) {
            addCriterion("open_account like", value, "open_account");
            return (Criteria) this;
        }

        public Criteria andOpen_accountNotLike(String value) {
            addCriterion("open_account not like", value, "open_account");
            return (Criteria) this;
        }

        public Criteria andOpen_accountIn(List<String> values) {
            addCriterion("open_account in", values, "open_account");
            return (Criteria) this;
        }

        public Criteria andOpen_accountNotIn(List<String> values) {
            addCriterion("open_account not in", values, "open_account");
            return (Criteria) this;
        }

        public Criteria andOpen_accountBetween(String value1, String value2) {
            addCriterion("open_account between", value1, value2, "open_account");
            return (Criteria) this;
        }

        public Criteria andOpen_accountNotBetween(String value1, String value2) {
            addCriterion("open_account not between", value1, value2, "open_account");
            return (Criteria) this;
        }

        public Criteria andUser_idIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUser_idIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUser_idEqualTo(Integer value) {
            addCriterion("user_id =", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idGreaterThan(Integer value) {
            addCriterion("user_id >", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idLessThan(Integer value) {
            addCriterion("user_id <", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idIn(List<Integer> values) {
            addCriterion("user_id in", values, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "user_id");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_invoice
     *
     * @mbg.generated do_not_delete_during_merge Wed Dec 18 11:24:48 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_invoice
     *
     * @mbg.generated Wed Dec 18 11:24:48 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}