package com.genetech.bean;

public class Invoice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invoice.id
     *
     * @mbg.generated Wed Dec 18 11:24:48 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invoice.title
     *
     * @mbg.generated Wed Dec 18 11:24:48 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invoice.taxpayer_number
     *
     * @mbg.generated Wed Dec 18 11:24:48 CST 2019
     */
    private String taxpayer_number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invoice.regist_address
     *
     * @mbg.generated Wed Dec 18 11:24:48 CST 2019
     */
    private String regist_address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invoice.regist_phone
     *
     * @mbg.generated Wed Dec 18 11:24:48 CST 2019
     */
    private String regist_phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invoice.open_bank
     *
     * @mbg.generated Wed Dec 18 11:24:48 CST 2019
     */
    private String open_bank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invoice.open_account
     *
     * @mbg.generated Wed Dec 18 11:24:48 CST 2019
     */
    private String open_account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invoice.user_id
     *
     * @mbg.generated Wed Dec 18 11:24:48 CST 2019
     */
    private Integer user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invoice.content
     *
     * @mbg.generated Wed Dec 18 11:24:48 CST 2019
     */
    private String content;

    public Invoice() {
    }

    public Invoice(Integer id, String title, String taxpayer_number, String regist_address, String regist_phone, String open_bank, String open_account, Integer user_id, String content) {
        this.id = id;
        this.title = title;
        this.taxpayer_number = taxpayer_number;
        this.regist_address = regist_address;
        this.regist_phone = regist_phone;
        this.open_bank = open_bank;
        this.open_account = open_account;
        this.user_id = user_id;
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invoice.id
     *
     * @return the value of t_invoice.id
     *
     * @mbg.generated Wed Dec 18 11:24:48 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invoice.id
     *
     * @param id the value for t_invoice.id
     *
     * @mbg.generated Wed Dec 18 11:24:48 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invoice.title
     *
     * @return the value of t_invoice.title
     *
     * @mbg.generated Wed Dec 18 11:24:48 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invoice.title
     *
     * @param title the value for t_invoice.title
     *
     * @mbg.generated Wed Dec 18 11:24:48 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invoice.taxpayer_number
     *
     * @return the value of t_invoice.taxpayer_number
     *
     * @mbg.generated Wed Dec 18 11:24:48 CST 2019
     */
    public String getTaxpayer_number() {
        return taxpayer_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invoice.taxpayer_number
     *
     * @param taxpayer_number the value for t_invoice.taxpayer_number
     *
     * @mbg.generated Wed Dec 18 11:24:48 CST 2019
     */
    public void setTaxpayer_number(String taxpayer_number) {
        this.taxpayer_number = taxpayer_number == null ? null : taxpayer_number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invoice.regist_address
     *
     * @return the value of t_invoice.regist_address
     *
     * @mbg.generated Wed Dec 18 11:24:48 CST 2019
     */
    public String getRegist_address() {
        return regist_address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invoice.regist_address
     *
     * @param regist_address the value for t_invoice.regist_address
     *
     * @mbg.generated Wed Dec 18 11:24:48 CST 2019
     */
    public void setRegist_address(String regist_address) {
        this.regist_address = regist_address == null ? null : regist_address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invoice.regist_phone
     *
     * @return the value of t_invoice.regist_phone
     *
     * @mbg.generated Wed Dec 18 11:24:48 CST 2019
     */
    public String getRegist_phone() {
        return regist_phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invoice.regist_phone
     *
     * @param regist_phone the value for t_invoice.regist_phone
     *
     * @mbg.generated Wed Dec 18 11:24:48 CST 2019
     */
    public void setRegist_phone(String regist_phone) {
        this.regist_phone = regist_phone == null ? null : regist_phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invoice.open_bank
     *
     * @return the value of t_invoice.open_bank
     *
     * @mbg.generated Wed Dec 18 11:24:48 CST 2019
     */
    public String getOpen_bank() {
        return open_bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invoice.open_bank
     *
     * @param open_bank the value for t_invoice.open_bank
     *
     * @mbg.generated Wed Dec 18 11:24:48 CST 2019
     */
    public void setOpen_bank(String open_bank) {
        this.open_bank = open_bank == null ? null : open_bank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invoice.open_account
     *
     * @return the value of t_invoice.open_account
     *
     * @mbg.generated Wed Dec 18 11:24:48 CST 2019
     */
    public String getOpen_account() {
        return open_account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invoice.open_account
     *
     * @param open_account the value for t_invoice.open_account
     *
     * @mbg.generated Wed Dec 18 11:24:48 CST 2019
     */
    public void setOpen_account(String open_account) {
        this.open_account = open_account == null ? null : open_account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invoice.user_id
     *
     * @return the value of t_invoice.user_id
     *
     * @mbg.generated Wed Dec 18 11:24:48 CST 2019
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invoice.user_id
     *
     * @param user_id the value for t_invoice.user_id
     *
     * @mbg.generated Wed Dec 18 11:24:48 CST 2019
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invoice.content
     *
     * @return the value of t_invoice.content
     *
     * @mbg.generated Wed Dec 18 11:24:48 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invoice.content
     *
     * @param content the value for t_invoice.content
     *
     * @mbg.generated Wed Dec 18 11:24:48 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }



}