package com.genetech.bean;

import java.util.ArrayList;
import java.util.List;

public class PlasmidDictExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_plasmid_dict
     *
     * @mbg.generated Sun Dec 29 15:10:25 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_plasmid_dict
     *
     * @mbg.generated Sun Dec 29 15:10:25 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_plasmid_dict
     *
     * @mbg.generated Sun Dec 29 15:10:25 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plasmid_dict
     *
     * @mbg.generated Sun Dec 29 15:10:25 CST 2019
     */
    public PlasmidDictExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plasmid_dict
     *
     * @mbg.generated Sun Dec 29 15:10:25 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plasmid_dict
     *
     * @mbg.generated Sun Dec 29 15:10:25 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plasmid_dict
     *
     * @mbg.generated Sun Dec 29 15:10:25 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plasmid_dict
     *
     * @mbg.generated Sun Dec 29 15:10:25 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plasmid_dict
     *
     * @mbg.generated Sun Dec 29 15:10:25 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plasmid_dict
     *
     * @mbg.generated Sun Dec 29 15:10:25 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plasmid_dict
     *
     * @mbg.generated Sun Dec 29 15:10:25 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plasmid_dict
     *
     * @mbg.generated Sun Dec 29 15:10:25 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plasmid_dict
     *
     * @mbg.generated Sun Dec 29 15:10:25 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plasmid_dict
     *
     * @mbg.generated Sun Dec 29 15:10:25 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_plasmid_dict
     *
     * @mbg.generated Sun Dec 29 15:10:25 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPlasmid_typeIsNull() {
            addCriterion("plasmid_type is null");
            return (Criteria) this;
        }

        public Criteria andPlasmid_typeIsNotNull() {
            addCriterion("plasmid_type is not null");
            return (Criteria) this;
        }

        public Criteria andPlasmid_typeEqualTo(String value) {
            addCriterion("plasmid_type =", value, "plasmid_type");
            return (Criteria) this;
        }

        public Criteria andPlasmid_typeNotEqualTo(String value) {
            addCriterion("plasmid_type <>", value, "plasmid_type");
            return (Criteria) this;
        }

        public Criteria andPlasmid_typeGreaterThan(String value) {
            addCriterion("plasmid_type >", value, "plasmid_type");
            return (Criteria) this;
        }

        public Criteria andPlasmid_typeGreaterThanOrEqualTo(String value) {
            addCriterion("plasmid_type >=", value, "plasmid_type");
            return (Criteria) this;
        }

        public Criteria andPlasmid_typeLessThan(String value) {
            addCriterion("plasmid_type <", value, "plasmid_type");
            return (Criteria) this;
        }

        public Criteria andPlasmid_typeLessThanOrEqualTo(String value) {
            addCriterion("plasmid_type <=", value, "plasmid_type");
            return (Criteria) this;
        }

        public Criteria andPlasmid_typeLike(String value) {
            addCriterion("plasmid_type like", value, "plasmid_type");
            return (Criteria) this;
        }

        public Criteria andPlasmid_typeNotLike(String value) {
            addCriterion("plasmid_type not like", value, "plasmid_type");
            return (Criteria) this;
        }

        public Criteria andPlasmid_typeIn(List<String> values) {
            addCriterion("plasmid_type in", values, "plasmid_type");
            return (Criteria) this;
        }

        public Criteria andPlasmid_typeNotIn(List<String> values) {
            addCriterion("plasmid_type not in", values, "plasmid_type");
            return (Criteria) this;
        }

        public Criteria andPlasmid_typeBetween(String value1, String value2) {
            addCriterion("plasmid_type between", value1, value2, "plasmid_type");
            return (Criteria) this;
        }

        public Criteria andPlasmid_typeNotBetween(String value1, String value2) {
            addCriterion("plasmid_type not between", value1, value2, "plasmid_type");
            return (Criteria) this;
        }

        public Criteria andGene_speciesIsNull() {
            addCriterion("gene_species is null");
            return (Criteria) this;
        }

        public Criteria andGene_speciesIsNotNull() {
            addCriterion("gene_species is not null");
            return (Criteria) this;
        }

        public Criteria andGene_speciesEqualTo(String value) {
            addCriterion("gene_species =", value, "gene_species");
            return (Criteria) this;
        }

        public Criteria andGene_speciesNotEqualTo(String value) {
            addCriterion("gene_species <>", value, "gene_species");
            return (Criteria) this;
        }

        public Criteria andGene_speciesGreaterThan(String value) {
            addCriterion("gene_species >", value, "gene_species");
            return (Criteria) this;
        }

        public Criteria andGene_speciesGreaterThanOrEqualTo(String value) {
            addCriterion("gene_species >=", value, "gene_species");
            return (Criteria) this;
        }

        public Criteria andGene_speciesLessThan(String value) {
            addCriterion("gene_species <", value, "gene_species");
            return (Criteria) this;
        }

        public Criteria andGene_speciesLessThanOrEqualTo(String value) {
            addCriterion("gene_species <=", value, "gene_species");
            return (Criteria) this;
        }

        public Criteria andGene_speciesLike(String value) {
            addCriterion("gene_species like", value, "gene_species");
            return (Criteria) this;
        }

        public Criteria andGene_speciesNotLike(String value) {
            addCriterion("gene_species not like", value, "gene_species");
            return (Criteria) this;
        }

        public Criteria andGene_speciesIn(List<String> values) {
            addCriterion("gene_species in", values, "gene_species");
            return (Criteria) this;
        }

        public Criteria andGene_speciesNotIn(List<String> values) {
            addCriterion("gene_species not in", values, "gene_species");
            return (Criteria) this;
        }

        public Criteria andGene_speciesBetween(String value1, String value2) {
            addCriterion("gene_species between", value1, value2, "gene_species");
            return (Criteria) this;
        }

        public Criteria andGene_speciesNotBetween(String value1, String value2) {
            addCriterion("gene_species not between", value1, value2, "gene_species");
            return (Criteria) this;
        }

        public Criteria andPlasmid_descriptionIsNull() {
            addCriterion("plasmid_description is null");
            return (Criteria) this;
        }

        public Criteria andPlasmid_descriptionIsNotNull() {
            addCriterion("plasmid_description is not null");
            return (Criteria) this;
        }

        public Criteria andPlasmid_descriptionEqualTo(String value) {
            addCriterion("plasmid_description =", value, "plasmid_description");
            return (Criteria) this;
        }

        public Criteria andPlasmid_descriptionNotEqualTo(String value) {
            addCriterion("plasmid_description <>", value, "plasmid_description");
            return (Criteria) this;
        }

        public Criteria andPlasmid_descriptionGreaterThan(String value) {
            addCriterion("plasmid_description >", value, "plasmid_description");
            return (Criteria) this;
        }

        public Criteria andPlasmid_descriptionGreaterThanOrEqualTo(String value) {
            addCriterion("plasmid_description >=", value, "plasmid_description");
            return (Criteria) this;
        }

        public Criteria andPlasmid_descriptionLessThan(String value) {
            addCriterion("plasmid_description <", value, "plasmid_description");
            return (Criteria) this;
        }

        public Criteria andPlasmid_descriptionLessThanOrEqualTo(String value) {
            addCriterion("plasmid_description <=", value, "plasmid_description");
            return (Criteria) this;
        }

        public Criteria andPlasmid_descriptionLike(String value) {
            addCriterion("plasmid_description like", value, "plasmid_description");
            return (Criteria) this;
        }

        public Criteria andPlasmid_descriptionNotLike(String value) {
            addCriterion("plasmid_description not like", value, "plasmid_description");
            return (Criteria) this;
        }

        public Criteria andPlasmid_descriptionIn(List<String> values) {
            addCriterion("plasmid_description in", values, "plasmid_description");
            return (Criteria) this;
        }

        public Criteria andPlasmid_descriptionNotIn(List<String> values) {
            addCriterion("plasmid_description not in", values, "plasmid_description");
            return (Criteria) this;
        }

        public Criteria andPlasmid_descriptionBetween(String value1, String value2) {
            addCriterion("plasmid_description between", value1, value2, "plasmid_description");
            return (Criteria) this;
        }

        public Criteria andPlasmid_descriptionNotBetween(String value1, String value2) {
            addCriterion("plasmid_description not between", value1, value2, "plasmid_description");
            return (Criteria) this;
        }

        public Criteria andGrowth_bacterial_resistanceIsNull() {
            addCriterion("growth_bacterial_resistance is null");
            return (Criteria) this;
        }

        public Criteria andGrowth_bacterial_resistanceIsNotNull() {
            addCriterion("growth_bacterial_resistance is not null");
            return (Criteria) this;
        }

        public Criteria andGrowth_bacterial_resistanceEqualTo(String value) {
            addCriterion("growth_bacterial_resistance =", value, "growth_bacterial_resistance");
            return (Criteria) this;
        }

        public Criteria andGrowth_bacterial_resistanceNotEqualTo(String value) {
            addCriterion("growth_bacterial_resistance <>", value, "growth_bacterial_resistance");
            return (Criteria) this;
        }

        public Criteria andGrowth_bacterial_resistanceGreaterThan(String value) {
            addCriterion("growth_bacterial_resistance >", value, "growth_bacterial_resistance");
            return (Criteria) this;
        }

        public Criteria andGrowth_bacterial_resistanceGreaterThanOrEqualTo(String value) {
            addCriterion("growth_bacterial_resistance >=", value, "growth_bacterial_resistance");
            return (Criteria) this;
        }

        public Criteria andGrowth_bacterial_resistanceLessThan(String value) {
            addCriterion("growth_bacterial_resistance <", value, "growth_bacterial_resistance");
            return (Criteria) this;
        }

        public Criteria andGrowth_bacterial_resistanceLessThanOrEqualTo(String value) {
            addCriterion("growth_bacterial_resistance <=", value, "growth_bacterial_resistance");
            return (Criteria) this;
        }

        public Criteria andGrowth_bacterial_resistanceLike(String value) {
            addCriterion("growth_bacterial_resistance like", value, "growth_bacterial_resistance");
            return (Criteria) this;
        }

        public Criteria andGrowth_bacterial_resistanceNotLike(String value) {
            addCriterion("growth_bacterial_resistance not like", value, "growth_bacterial_resistance");
            return (Criteria) this;
        }

        public Criteria andGrowth_bacterial_resistanceIn(List<String> values) {
            addCriterion("growth_bacterial_resistance in", values, "growth_bacterial_resistance");
            return (Criteria) this;
        }

        public Criteria andGrowth_bacterial_resistanceNotIn(List<String> values) {
            addCriterion("growth_bacterial_resistance not in", values, "growth_bacterial_resistance");
            return (Criteria) this;
        }

        public Criteria andGrowth_bacterial_resistanceBetween(String value1, String value2) {
            addCriterion("growth_bacterial_resistance between", value1, value2, "growth_bacterial_resistance");
            return (Criteria) this;
        }

        public Criteria andGrowth_bacterial_resistanceNotBetween(String value1, String value2) {
            addCriterion("growth_bacterial_resistance not between", value1, value2, "growth_bacterial_resistance");
            return (Criteria) this;
        }

        public Criteria andPlasmid_type_otherIsNull() {
            addCriterion("plasmid_type_other is null");
            return (Criteria) this;
        }

        public Criteria andPlasmid_type_otherIsNotNull() {
            addCriterion("plasmid_type_other is not null");
            return (Criteria) this;
        }

        public Criteria andPlasmid_type_otherEqualTo(String value) {
            addCriterion("plasmid_type_other =", value, "plasmid_type_other");
            return (Criteria) this;
        }

        public Criteria andPlasmid_type_otherNotEqualTo(String value) {
            addCriterion("plasmid_type_other <>", value, "plasmid_type_other");
            return (Criteria) this;
        }

        public Criteria andPlasmid_type_otherGreaterThan(String value) {
            addCriterion("plasmid_type_other >", value, "plasmid_type_other");
            return (Criteria) this;
        }

        public Criteria andPlasmid_type_otherGreaterThanOrEqualTo(String value) {
            addCriterion("plasmid_type_other >=", value, "plasmid_type_other");
            return (Criteria) this;
        }

        public Criteria andPlasmid_type_otherLessThan(String value) {
            addCriterion("plasmid_type_other <", value, "plasmid_type_other");
            return (Criteria) this;
        }

        public Criteria andPlasmid_type_otherLessThanOrEqualTo(String value) {
            addCriterion("plasmid_type_other <=", value, "plasmid_type_other");
            return (Criteria) this;
        }

        public Criteria andPlasmid_type_otherLike(String value) {
            addCriterion("plasmid_type_other like", value, "plasmid_type_other");
            return (Criteria) this;
        }

        public Criteria andPlasmid_type_otherNotLike(String value) {
            addCriterion("plasmid_type_other not like", value, "plasmid_type_other");
            return (Criteria) this;
        }

        public Criteria andPlasmid_type_otherIn(List<String> values) {
            addCriterion("plasmid_type_other in", values, "plasmid_type_other");
            return (Criteria) this;
        }

        public Criteria andPlasmid_type_otherNotIn(List<String> values) {
            addCriterion("plasmid_type_other not in", values, "plasmid_type_other");
            return (Criteria) this;
        }

        public Criteria andPlasmid_type_otherBetween(String value1, String value2) {
            addCriterion("plasmid_type_other between", value1, value2, "plasmid_type_other");
            return (Criteria) this;
        }

        public Criteria andPlasmid_type_otherNotBetween(String value1, String value2) {
            addCriterion("plasmid_type_other not between", value1, value2, "plasmid_type_other");
            return (Criteria) this;
        }

        public Criteria andGene_species_otherIsNull() {
            addCriterion("gene_species_other is null");
            return (Criteria) this;
        }

        public Criteria andGene_species_otherIsNotNull() {
            addCriterion("gene_species_other is not null");
            return (Criteria) this;
        }

        public Criteria andGene_species_otherEqualTo(String value) {
            addCriterion("gene_species_other =", value, "gene_species_other");
            return (Criteria) this;
        }

        public Criteria andGene_species_otherNotEqualTo(String value) {
            addCriterion("gene_species_other <>", value, "gene_species_other");
            return (Criteria) this;
        }

        public Criteria andGene_species_otherGreaterThan(String value) {
            addCriterion("gene_species_other >", value, "gene_species_other");
            return (Criteria) this;
        }

        public Criteria andGene_species_otherGreaterThanOrEqualTo(String value) {
            addCriterion("gene_species_other >=", value, "gene_species_other");
            return (Criteria) this;
        }

        public Criteria andGene_species_otherLessThan(String value) {
            addCriterion("gene_species_other <", value, "gene_species_other");
            return (Criteria) this;
        }

        public Criteria andGene_species_otherLessThanOrEqualTo(String value) {
            addCriterion("gene_species_other <=", value, "gene_species_other");
            return (Criteria) this;
        }

        public Criteria andGene_species_otherLike(String value) {
            addCriterion("gene_species_other like", value, "gene_species_other");
            return (Criteria) this;
        }

        public Criteria andGene_species_otherNotLike(String value) {
            addCriterion("gene_species_other not like", value, "gene_species_other");
            return (Criteria) this;
        }

        public Criteria andGene_species_otherIn(List<String> values) {
            addCriterion("gene_species_other in", values, "gene_species_other");
            return (Criteria) this;
        }

        public Criteria andGene_species_otherNotIn(List<String> values) {
            addCriterion("gene_species_other not in", values, "gene_species_other");
            return (Criteria) this;
        }

        public Criteria andGene_species_otherBetween(String value1, String value2) {
            addCriterion("gene_species_other between", value1, value2, "gene_species_other");
            return (Criteria) this;
        }

        public Criteria andGene_species_otherNotBetween(String value1, String value2) {
            addCriterion("gene_species_other not between", value1, value2, "gene_species_other");
            return (Criteria) this;
        }

        public Criteria andPlasmid_description_otherIsNull() {
            addCriterion("plasmid_description_other is null");
            return (Criteria) this;
        }

        public Criteria andPlasmid_description_otherIsNotNull() {
            addCriterion("plasmid_description_other is not null");
            return (Criteria) this;
        }

        public Criteria andPlasmid_description_otherEqualTo(String value) {
            addCriterion("plasmid_description_other =", value, "plasmid_description_other");
            return (Criteria) this;
        }

        public Criteria andPlasmid_description_otherNotEqualTo(String value) {
            addCriterion("plasmid_description_other <>", value, "plasmid_description_other");
            return (Criteria) this;
        }

        public Criteria andPlasmid_description_otherGreaterThan(String value) {
            addCriterion("plasmid_description_other >", value, "plasmid_description_other");
            return (Criteria) this;
        }

        public Criteria andPlasmid_description_otherGreaterThanOrEqualTo(String value) {
            addCriterion("plasmid_description_other >=", value, "plasmid_description_other");
            return (Criteria) this;
        }

        public Criteria andPlasmid_description_otherLessThan(String value) {
            addCriterion("plasmid_description_other <", value, "plasmid_description_other");
            return (Criteria) this;
        }

        public Criteria andPlasmid_description_otherLessThanOrEqualTo(String value) {
            addCriterion("plasmid_description_other <=", value, "plasmid_description_other");
            return (Criteria) this;
        }

        public Criteria andPlasmid_description_otherLike(String value) {
            addCriterion("plasmid_description_other like", value, "plasmid_description_other");
            return (Criteria) this;
        }

        public Criteria andPlasmid_description_otherNotLike(String value) {
            addCriterion("plasmid_description_other not like", value, "plasmid_description_other");
            return (Criteria) this;
        }

        public Criteria andPlasmid_description_otherIn(List<String> values) {
            addCriterion("plasmid_description_other in", values, "plasmid_description_other");
            return (Criteria) this;
        }

        public Criteria andPlasmid_description_otherNotIn(List<String> values) {
            addCriterion("plasmid_description_other not in", values, "plasmid_description_other");
            return (Criteria) this;
        }

        public Criteria andPlasmid_description_otherBetween(String value1, String value2) {
            addCriterion("plasmid_description_other between", value1, value2, "plasmid_description_other");
            return (Criteria) this;
        }

        public Criteria andPlasmid_description_otherNotBetween(String value1, String value2) {
            addCriterion("plasmid_description_other not between", value1, value2, "plasmid_description_other");
            return (Criteria) this;
        }

        public Criteria andGrowth_bacterial_resistance_otherIsNull() {
            addCriterion("growth_bacterial_resistance_other is null");
            return (Criteria) this;
        }

        public Criteria andGrowth_bacterial_resistance_otherIsNotNull() {
            addCriterion("growth_bacterial_resistance_other is not null");
            return (Criteria) this;
        }

        public Criteria andGrowth_bacterial_resistance_otherEqualTo(String value) {
            addCriterion("growth_bacterial_resistance_other =", value, "growth_bacterial_resistance_other");
            return (Criteria) this;
        }

        public Criteria andGrowth_bacterial_resistance_otherNotEqualTo(String value) {
            addCriterion("growth_bacterial_resistance_other <>", value, "growth_bacterial_resistance_other");
            return (Criteria) this;
        }

        public Criteria andGrowth_bacterial_resistance_otherGreaterThan(String value) {
            addCriterion("growth_bacterial_resistance_other >", value, "growth_bacterial_resistance_other");
            return (Criteria) this;
        }

        public Criteria andGrowth_bacterial_resistance_otherGreaterThanOrEqualTo(String value) {
            addCriterion("growth_bacterial_resistance_other >=", value, "growth_bacterial_resistance_other");
            return (Criteria) this;
        }

        public Criteria andGrowth_bacterial_resistance_otherLessThan(String value) {
            addCriterion("growth_bacterial_resistance_other <", value, "growth_bacterial_resistance_other");
            return (Criteria) this;
        }

        public Criteria andGrowth_bacterial_resistance_otherLessThanOrEqualTo(String value) {
            addCriterion("growth_bacterial_resistance_other <=", value, "growth_bacterial_resistance_other");
            return (Criteria) this;
        }

        public Criteria andGrowth_bacterial_resistance_otherLike(String value) {
            addCriterion("growth_bacterial_resistance_other like", value, "growth_bacterial_resistance_other");
            return (Criteria) this;
        }

        public Criteria andGrowth_bacterial_resistance_otherNotLike(String value) {
            addCriterion("growth_bacterial_resistance_other not like", value, "growth_bacterial_resistance_other");
            return (Criteria) this;
        }

        public Criteria andGrowth_bacterial_resistance_otherIn(List<String> values) {
            addCriterion("growth_bacterial_resistance_other in", values, "growth_bacterial_resistance_other");
            return (Criteria) this;
        }

        public Criteria andGrowth_bacterial_resistance_otherNotIn(List<String> values) {
            addCriterion("growth_bacterial_resistance_other not in", values, "growth_bacterial_resistance_other");
            return (Criteria) this;
        }

        public Criteria andGrowth_bacterial_resistance_otherBetween(String value1, String value2) {
            addCriterion("growth_bacterial_resistance_other between", value1, value2, "growth_bacterial_resistance_other");
            return (Criteria) this;
        }

        public Criteria andGrowth_bacterial_resistance_otherNotBetween(String value1, String value2) {
            addCriterion("growth_bacterial_resistance_other not between", value1, value2, "growth_bacterial_resistance_other");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_plasmid_dict
     *
     * @mbg.generated do_not_delete_during_merge Sun Dec 29 15:10:25 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_plasmid_dict
     *
     * @mbg.generated Sun Dec 29 15:10:25 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}