package com.genetech.bean;

import java.util.ArrayList;
import java.util.List;

public class PlasmidExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_plasmid_info
     *
     * @mbg.generated Wed Dec 18 15:54:37 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_plasmid_info
     *
     * @mbg.generated Wed Dec 18 15:54:37 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_plasmid_info
     *
     * @mbg.generated Wed Dec 18 15:54:37 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plasmid_info
     *
     * @mbg.generated Wed Dec 18 15:54:37 CST 2019
     */
    public PlasmidExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plasmid_info
     *
     * @mbg.generated Wed Dec 18 15:54:37 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plasmid_info
     *
     * @mbg.generated Wed Dec 18 15:54:37 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plasmid_info
     *
     * @mbg.generated Wed Dec 18 15:54:37 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plasmid_info
     *
     * @mbg.generated Wed Dec 18 15:54:37 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plasmid_info
     *
     * @mbg.generated Wed Dec 18 15:54:37 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plasmid_info
     *
     * @mbg.generated Wed Dec 18 15:54:37 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plasmid_info
     *
     * @mbg.generated Wed Dec 18 15:54:37 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plasmid_info
     *
     * @mbg.generated Wed Dec 18 15:54:37 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plasmid_info
     *
     * @mbg.generated Wed Dec 18 15:54:37 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plasmid_info
     *
     * @mbg.generated Wed Dec 18 15:54:37 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_plasmid_info
     *
     * @mbg.generated Wed Dec 18 15:54:37 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPlasmid_identificationIsNull() {
            addCriterion("plasmid_identification is null");
            return (Criteria) this;
        }

        public Criteria andPlasmid_identificationIsNotNull() {
            addCriterion("plasmid_identification is not null");
            return (Criteria) this;
        }

        public Criteria andPlasmid_identificationEqualTo(String value) {
            addCriterion("plasmid_identification =", value, "plasmid_identification");
            return (Criteria) this;
        }

        public Criteria andPlasmid_identificationNotEqualTo(String value) {
            addCriterion("plasmid_identification <>", value, "plasmid_identification");
            return (Criteria) this;
        }

        public Criteria andPlasmid_identificationGreaterThan(String value) {
            addCriterion("plasmid_identification >", value, "plasmid_identification");
            return (Criteria) this;
        }

        public Criteria andPlasmid_identificationGreaterThanOrEqualTo(String value) {
            addCriterion("plasmid_identification >=", value, "plasmid_identification");
            return (Criteria) this;
        }

        public Criteria andPlasmid_identificationLessThan(String value) {
            addCriterion("plasmid_identification <", value, "plasmid_identification");
            return (Criteria) this;
        }

        public Criteria andPlasmid_identificationLessThanOrEqualTo(String value) {
            addCriterion("plasmid_identification <=", value, "plasmid_identification");
            return (Criteria) this;
        }

        public Criteria andPlasmid_identificationLike(String value) {
            addCriterion("plasmid_identification like", value, "plasmid_identification");
            return (Criteria) this;
        }

        public Criteria andPlasmid_identificationNotLike(String value) {
            addCriterion("plasmid_identification not like", value, "plasmid_identification");
            return (Criteria) this;
        }

        public Criteria andPlasmid_identificationIn(List<String> values) {
            addCriterion("plasmid_identification in", values, "plasmid_identification");
            return (Criteria) this;
        }

        public Criteria andPlasmid_identificationNotIn(List<String> values) {
            addCriterion("plasmid_identification not in", values, "plasmid_identification");
            return (Criteria) this;
        }

        public Criteria andPlasmid_identificationBetween(String value1, String value2) {
            addCriterion("plasmid_identification between", value1, value2, "plasmid_identification");
            return (Criteria) this;
        }

        public Criteria andPlasmid_identificationNotBetween(String value1, String value2) {
            addCriterion("plasmid_identification not between", value1, value2, "plasmid_identification");
            return (Criteria) this;
        }

        public Criteria andPlasmid_nameIsNull() {
            addCriterion("plasmid_name is null");
            return (Criteria) this;
        }

        public Criteria andPlasmid_nameIsNotNull() {
            addCriterion("plasmid_name is not null");
            return (Criteria) this;
        }

        public Criteria andPlasmid_nameEqualTo(String value) {
            addCriterion("plasmid_name =", value, "plasmid_name");
            return (Criteria) this;
        }

        public Criteria andPlasmid_nameNotEqualTo(String value) {
            addCriterion("plasmid_name <>", value, "plasmid_name");
            return (Criteria) this;
        }

        public Criteria andPlasmid_nameGreaterThan(String value) {
            addCriterion("plasmid_name >", value, "plasmid_name");
            return (Criteria) this;
        }

        public Criteria andPlasmid_nameGreaterThanOrEqualTo(String value) {
            addCriterion("plasmid_name >=", value, "plasmid_name");
            return (Criteria) this;
        }

        public Criteria andPlasmid_nameLessThan(String value) {
            addCriterion("plasmid_name <", value, "plasmid_name");
            return (Criteria) this;
        }

        public Criteria andPlasmid_nameLessThanOrEqualTo(String value) {
            addCriterion("plasmid_name <=", value, "plasmid_name");
            return (Criteria) this;
        }

        public Criteria andPlasmid_nameLike(String value) {
            addCriterion("plasmid_name like", value, "plasmid_name");
            return (Criteria) this;
        }

        public Criteria andPlasmid_nameNotLike(String value) {
            addCriterion("plasmid_name not like", value, "plasmid_name");
            return (Criteria) this;
        }

        public Criteria andPlasmid_nameIn(List<String> values) {
            addCriterion("plasmid_name in", values, "plasmid_name");
            return (Criteria) this;
        }

        public Criteria andPlasmid_nameNotIn(List<String> values) {
            addCriterion("plasmid_name not in", values, "plasmid_name");
            return (Criteria) this;
        }

        public Criteria andPlasmid_nameBetween(String value1, String value2) {
            addCriterion("plasmid_name between", value1, value2, "plasmid_name");
            return (Criteria) this;
        }

        public Criteria andPlasmid_nameNotBetween(String value1, String value2) {
            addCriterion("plasmid_name not between", value1, value2, "plasmid_name");
            return (Criteria) this;
        }

        public Criteria andPlasmid_sizeIsNull() {
            addCriterion("plasmid_size is null");
            return (Criteria) this;
        }

        public Criteria andPlasmid_sizeIsNotNull() {
            addCriterion("plasmid_size is not null");
            return (Criteria) this;
        }

        public Criteria andPlasmid_sizeEqualTo(String value) {
            addCriterion("plasmid_size =", value, "plasmid_size");
            return (Criteria) this;
        }

        public Criteria andPlasmid_sizeNotEqualTo(String value) {
            addCriterion("plasmid_size <>", value, "plasmid_size");
            return (Criteria) this;
        }

        public Criteria andPlasmid_sizeGreaterThan(String value) {
            addCriterion("plasmid_size >", value, "plasmid_size");
            return (Criteria) this;
        }

        public Criteria andPlasmid_sizeGreaterThanOrEqualTo(String value) {
            addCriterion("plasmid_size >=", value, "plasmid_size");
            return (Criteria) this;
        }

        public Criteria andPlasmid_sizeLessThan(String value) {
            addCriterion("plasmid_size <", value, "plasmid_size");
            return (Criteria) this;
        }

        public Criteria andPlasmid_sizeLessThanOrEqualTo(String value) {
            addCriterion("plasmid_size <=", value, "plasmid_size");
            return (Criteria) this;
        }

        public Criteria andPlasmid_sizeLike(String value) {
            addCriterion("plasmid_size like", value, "plasmid_size");
            return (Criteria) this;
        }

        public Criteria andPlasmid_sizeNotLike(String value) {
            addCriterion("plasmid_size not like", value, "plasmid_size");
            return (Criteria) this;
        }

        public Criteria andPlasmid_sizeIn(List<String> values) {
            addCriterion("plasmid_size in", values, "plasmid_size");
            return (Criteria) this;
        }

        public Criteria andPlasmid_sizeNotIn(List<String> values) {
            addCriterion("plasmid_size not in", values, "plasmid_size");
            return (Criteria) this;
        }

        public Criteria andPlasmid_sizeBetween(String value1, String value2) {
            addCriterion("plasmid_size between", value1, value2, "plasmid_size");
            return (Criteria) this;
        }

        public Criteria andPlasmid_sizeNotBetween(String value1, String value2) {
            addCriterion("plasmid_size not between", value1, value2, "plasmid_size");
            return (Criteria) this;
        }

        public Criteria andLab_nameIsNull() {
            addCriterion("lab_name is null");
            return (Criteria) this;
        }

        public Criteria andLab_nameIsNotNull() {
            addCriterion("lab_name is not null");
            return (Criteria) this;
        }

        public Criteria andLab_nameEqualTo(String value) {
            addCriterion("lab_name =", value, "lab_name");
            return (Criteria) this;
        }

        public Criteria andLab_nameNotEqualTo(String value) {
            addCriterion("lab_name <>", value, "lab_name");
            return (Criteria) this;
        }

        public Criteria andLab_nameGreaterThan(String value) {
            addCriterion("lab_name >", value, "lab_name");
            return (Criteria) this;
        }

        public Criteria andLab_nameGreaterThanOrEqualTo(String value) {
            addCriterion("lab_name >=", value, "lab_name");
            return (Criteria) this;
        }

        public Criteria andLab_nameLessThan(String value) {
            addCriterion("lab_name <", value, "lab_name");
            return (Criteria) this;
        }

        public Criteria andLab_nameLessThanOrEqualTo(String value) {
            addCriterion("lab_name <=", value, "lab_name");
            return (Criteria) this;
        }

        public Criteria andLab_nameLike(String value) {
            addCriterion("lab_name like", value, "lab_name");
            return (Criteria) this;
        }

        public Criteria andLab_nameNotLike(String value) {
            addCriterion("lab_name not like", value, "lab_name");
            return (Criteria) this;
        }

        public Criteria andLab_nameIn(List<String> values) {
            addCriterion("lab_name in", values, "lab_name");
            return (Criteria) this;
        }

        public Criteria andLab_nameNotIn(List<String> values) {
            addCriterion("lab_name not in", values, "lab_name");
            return (Criteria) this;
        }

        public Criteria andLab_nameBetween(String value1, String value2) {
            addCriterion("lab_name between", value1, value2, "lab_name");
            return (Criteria) this;
        }

        public Criteria andLab_nameNotBetween(String value1, String value2) {
            addCriterion("lab_name not between", value1, value2, "lab_name");
            return (Criteria) this;
        }

        public Criteria andPlasmid_typeIsNull() {
            addCriterion("plasmid_type is null");
            return (Criteria) this;
        }

        public Criteria andPlasmid_typeIsNotNull() {
            addCriterion("plasmid_type is not null");
            return (Criteria) this;
        }

        public Criteria andPlasmid_typeEqualTo(String value) {
            addCriterion("plasmid_type =", value, "plasmid_type");
            return (Criteria) this;
        }

        public Criteria andPlasmid_typeNotEqualTo(String value) {
            addCriterion("plasmid_type <>", value, "plasmid_type");
            return (Criteria) this;
        }

        public Criteria andPlasmid_typeGreaterThan(String value) {
            addCriterion("plasmid_type >", value, "plasmid_type");
            return (Criteria) this;
        }

        public Criteria andPlasmid_typeGreaterThanOrEqualTo(String value) {
            addCriterion("plasmid_type >=", value, "plasmid_type");
            return (Criteria) this;
        }

        public Criteria andPlasmid_typeLessThan(String value) {
            addCriterion("plasmid_type <", value, "plasmid_type");
            return (Criteria) this;
        }

        public Criteria andPlasmid_typeLessThanOrEqualTo(String value) {
            addCriterion("plasmid_type <=", value, "plasmid_type");
            return (Criteria) this;
        }

        public Criteria andPlasmid_typeLike(String value) {
            addCriterion("plasmid_type like", value, "plasmid_type");
            return (Criteria) this;
        }

        public Criteria andPlasmid_typeNotLike(String value) {
            addCriterion("plasmid_type not like", value, "plasmid_type");
            return (Criteria) this;
        }

        public Criteria andPlasmid_typeIn(List<String> values) {
            addCriterion("plasmid_type in", values, "plasmid_type");
            return (Criteria) this;
        }

        public Criteria andPlasmid_typeNotIn(List<String> values) {
            addCriterion("plasmid_type not in", values, "plasmid_type");
            return (Criteria) this;
        }

        public Criteria andPlasmid_typeBetween(String value1, String value2) {
            addCriterion("plasmid_type between", value1, value2, "plasmid_type");
            return (Criteria) this;
        }

        public Criteria andPlasmid_typeNotBetween(String value1, String value2) {
            addCriterion("plasmid_type not between", value1, value2, "plasmid_type");
            return (Criteria) this;
        }

        public Criteria andPlasmid_user_restrictionIsNull() {
            addCriterion("plasmid_user_restriction is null");
            return (Criteria) this;
        }

        public Criteria andPlasmid_user_restrictionIsNotNull() {
            addCriterion("plasmid_user_restriction is not null");
            return (Criteria) this;
        }

        public Criteria andPlasmid_user_restrictionEqualTo(String value) {
            addCriterion("plasmid_user_restriction =", value, "plasmid_user_restriction");
            return (Criteria) this;
        }

        public Criteria andPlasmid_user_restrictionNotEqualTo(String value) {
            addCriterion("plasmid_user_restriction <>", value, "plasmid_user_restriction");
            return (Criteria) this;
        }

        public Criteria andPlasmid_user_restrictionGreaterThan(String value) {
            addCriterion("plasmid_user_restriction >", value, "plasmid_user_restriction");
            return (Criteria) this;
        }

        public Criteria andPlasmid_user_restrictionGreaterThanOrEqualTo(String value) {
            addCriterion("plasmid_user_restriction >=", value, "plasmid_user_restriction");
            return (Criteria) this;
        }

        public Criteria andPlasmid_user_restrictionLessThan(String value) {
            addCriterion("plasmid_user_restriction <", value, "plasmid_user_restriction");
            return (Criteria) this;
        }

        public Criteria andPlasmid_user_restrictionLessThanOrEqualTo(String value) {
            addCriterion("plasmid_user_restriction <=", value, "plasmid_user_restriction");
            return (Criteria) this;
        }

        public Criteria andPlasmid_user_restrictionLike(String value) {
            addCriterion("plasmid_user_restriction like", value, "plasmid_user_restriction");
            return (Criteria) this;
        }

        public Criteria andPlasmid_user_restrictionNotLike(String value) {
            addCriterion("plasmid_user_restriction not like", value, "plasmid_user_restriction");
            return (Criteria) this;
        }

        public Criteria andPlasmid_user_restrictionIn(List<String> values) {
            addCriterion("plasmid_user_restriction in", values, "plasmid_user_restriction");
            return (Criteria) this;
        }

        public Criteria andPlasmid_user_restrictionNotIn(List<String> values) {
            addCriterion("plasmid_user_restriction not in", values, "plasmid_user_restriction");
            return (Criteria) this;
        }

        public Criteria andPlasmid_user_restrictionBetween(String value1, String value2) {
            addCriterion("plasmid_user_restriction between", value1, value2, "plasmid_user_restriction");
            return (Criteria) this;
        }

        public Criteria andPlasmid_user_restrictionNotBetween(String value1, String value2) {
            addCriterion("plasmid_user_restriction not between", value1, value2, "plasmid_user_restriction");
            return (Criteria) this;
        }

        public Criteria andPlasmid_submit_typeIsNull() {
            addCriterion("plasmid_submit_type is null");
            return (Criteria) this;
        }

        public Criteria andPlasmid_submit_typeIsNotNull() {
            addCriterion("plasmid_submit_type is not null");
            return (Criteria) this;
        }

        public Criteria andPlasmid_submit_typeEqualTo(String value) {
            addCriterion("plasmid_submit_type =", value, "plasmid_submit_type");
            return (Criteria) this;
        }

        public Criteria andPlasmid_submit_typeNotEqualTo(String value) {
            addCriterion("plasmid_submit_type <>", value, "plasmid_submit_type");
            return (Criteria) this;
        }

        public Criteria andPlasmid_submit_typeGreaterThan(String value) {
            addCriterion("plasmid_submit_type >", value, "plasmid_submit_type");
            return (Criteria) this;
        }

        public Criteria andPlasmid_submit_typeGreaterThanOrEqualTo(String value) {
            addCriterion("plasmid_submit_type >=", value, "plasmid_submit_type");
            return (Criteria) this;
        }

        public Criteria andPlasmid_submit_typeLessThan(String value) {
            addCriterion("plasmid_submit_type <", value, "plasmid_submit_type");
            return (Criteria) this;
        }

        public Criteria andPlasmid_submit_typeLessThanOrEqualTo(String value) {
            addCriterion("plasmid_submit_type <=", value, "plasmid_submit_type");
            return (Criteria) this;
        }

        public Criteria andPlasmid_submit_typeLike(String value) {
            addCriterion("plasmid_submit_type like", value, "plasmid_submit_type");
            return (Criteria) this;
        }

        public Criteria andPlasmid_submit_typeNotLike(String value) {
            addCriterion("plasmid_submit_type not like", value, "plasmid_submit_type");
            return (Criteria) this;
        }

        public Criteria andPlasmid_submit_typeIn(List<String> values) {
            addCriterion("plasmid_submit_type in", values, "plasmid_submit_type");
            return (Criteria) this;
        }

        public Criteria andPlasmid_submit_typeNotIn(List<String> values) {
            addCriterion("plasmid_submit_type not in", values, "plasmid_submit_type");
            return (Criteria) this;
        }

        public Criteria andPlasmid_submit_typeBetween(String value1, String value2) {
            addCriterion("plasmid_submit_type between", value1, value2, "plasmid_submit_type");
            return (Criteria) this;
        }

        public Criteria andPlasmid_submit_typeNotBetween(String value1, String value2) {
            addCriterion("plasmid_submit_type not between", value1, value2, "plasmid_submit_type");
            return (Criteria) this;
        }

        public Criteria andGene_nameIsNull() {
            addCriterion("gene_name is null");
            return (Criteria) this;
        }

        public Criteria andGene_nameIsNotNull() {
            addCriterion("gene_name is not null");
            return (Criteria) this;
        }

        public Criteria andGene_nameEqualTo(String value) {
            addCriterion("gene_name =", value, "gene_name");
            return (Criteria) this;
        }

        public Criteria andGene_nameNotEqualTo(String value) {
            addCriterion("gene_name <>", value, "gene_name");
            return (Criteria) this;
        }

        public Criteria andGene_nameGreaterThan(String value) {
            addCriterion("gene_name >", value, "gene_name");
            return (Criteria) this;
        }

        public Criteria andGene_nameGreaterThanOrEqualTo(String value) {
            addCriterion("gene_name >=", value, "gene_name");
            return (Criteria) this;
        }

        public Criteria andGene_nameLessThan(String value) {
            addCriterion("gene_name <", value, "gene_name");
            return (Criteria) this;
        }

        public Criteria andGene_nameLessThanOrEqualTo(String value) {
            addCriterion("gene_name <=", value, "gene_name");
            return (Criteria) this;
        }

        public Criteria andGene_nameLike(String value) {
            addCriterion("gene_name like", value, "gene_name");
            return (Criteria) this;
        }

        public Criteria andGene_nameNotLike(String value) {
            addCriterion("gene_name not like", value, "gene_name");
            return (Criteria) this;
        }

        public Criteria andGene_nameIn(List<String> values) {
            addCriterion("gene_name in", values, "gene_name");
            return (Criteria) this;
        }

        public Criteria andGene_nameNotIn(List<String> values) {
            addCriterion("gene_name not in", values, "gene_name");
            return (Criteria) this;
        }

        public Criteria andGene_nameBetween(String value1, String value2) {
            addCriterion("gene_name between", value1, value2, "gene_name");
            return (Criteria) this;
        }

        public Criteria andGene_nameNotBetween(String value1, String value2) {
            addCriterion("gene_name not between", value1, value2, "gene_name");
            return (Criteria) this;
        }

        public Criteria andGene_alter_nameIsNull() {
            addCriterion("gene_alter_name is null");
            return (Criteria) this;
        }

        public Criteria andGene_alter_nameIsNotNull() {
            addCriterion("gene_alter_name is not null");
            return (Criteria) this;
        }

        public Criteria andGene_alter_nameEqualTo(String value) {
            addCriterion("gene_alter_name =", value, "gene_alter_name");
            return (Criteria) this;
        }

        public Criteria andGene_alter_nameNotEqualTo(String value) {
            addCriterion("gene_alter_name <>", value, "gene_alter_name");
            return (Criteria) this;
        }

        public Criteria andGene_alter_nameGreaterThan(String value) {
            addCriterion("gene_alter_name >", value, "gene_alter_name");
            return (Criteria) this;
        }

        public Criteria andGene_alter_nameGreaterThanOrEqualTo(String value) {
            addCriterion("gene_alter_name >=", value, "gene_alter_name");
            return (Criteria) this;
        }

        public Criteria andGene_alter_nameLessThan(String value) {
            addCriterion("gene_alter_name <", value, "gene_alter_name");
            return (Criteria) this;
        }

        public Criteria andGene_alter_nameLessThanOrEqualTo(String value) {
            addCriterion("gene_alter_name <=", value, "gene_alter_name");
            return (Criteria) this;
        }

        public Criteria andGene_alter_nameLike(String value) {
            addCriterion("gene_alter_name like", value, "gene_alter_name");
            return (Criteria) this;
        }

        public Criteria andGene_alter_nameNotLike(String value) {
            addCriterion("gene_alter_name not like", value, "gene_alter_name");
            return (Criteria) this;
        }

        public Criteria andGene_alter_nameIn(List<String> values) {
            addCriterion("gene_alter_name in", values, "gene_alter_name");
            return (Criteria) this;
        }

        public Criteria andGene_alter_nameNotIn(List<String> values) {
            addCriterion("gene_alter_name not in", values, "gene_alter_name");
            return (Criteria) this;
        }

        public Criteria andGene_alter_nameBetween(String value1, String value2) {
            addCriterion("gene_alter_name between", value1, value2, "gene_alter_name");
            return (Criteria) this;
        }

        public Criteria andGene_alter_nameNotBetween(String value1, String value2) {
            addCriterion("gene_alter_name not between", value1, value2, "gene_alter_name");
            return (Criteria) this;
        }

        public Criteria andGene_identificationIsNull() {
            addCriterion("gene_identification is null");
            return (Criteria) this;
        }

        public Criteria andGene_identificationIsNotNull() {
            addCriterion("gene_identification is not null");
            return (Criteria) this;
        }

        public Criteria andGene_identificationEqualTo(String value) {
            addCriterion("gene_identification =", value, "gene_identification");
            return (Criteria) this;
        }

        public Criteria andGene_identificationNotEqualTo(String value) {
            addCriterion("gene_identification <>", value, "gene_identification");
            return (Criteria) this;
        }

        public Criteria andGene_identificationGreaterThan(String value) {
            addCriterion("gene_identification >", value, "gene_identification");
            return (Criteria) this;
        }

        public Criteria andGene_identificationGreaterThanOrEqualTo(String value) {
            addCriterion("gene_identification >=", value, "gene_identification");
            return (Criteria) this;
        }

        public Criteria andGene_identificationLessThan(String value) {
            addCriterion("gene_identification <", value, "gene_identification");
            return (Criteria) this;
        }

        public Criteria andGene_identificationLessThanOrEqualTo(String value) {
            addCriterion("gene_identification <=", value, "gene_identification");
            return (Criteria) this;
        }

        public Criteria andGene_identificationLike(String value) {
            addCriterion("gene_identification like", value, "gene_identification");
            return (Criteria) this;
        }

        public Criteria andGene_identificationNotLike(String value) {
            addCriterion("gene_identification not like", value, "gene_identification");
            return (Criteria) this;
        }

        public Criteria andGene_identificationIn(List<String> values) {
            addCriterion("gene_identification in", values, "gene_identification");
            return (Criteria) this;
        }

        public Criteria andGene_identificationNotIn(List<String> values) {
            addCriterion("gene_identification not in", values, "gene_identification");
            return (Criteria) this;
        }

        public Criteria andGene_identificationBetween(String value1, String value2) {
            addCriterion("gene_identification between", value1, value2, "gene_identification");
            return (Criteria) this;
        }

        public Criteria andGene_identificationNotBetween(String value1, String value2) {
            addCriterion("gene_identification not between", value1, value2, "gene_identification");
            return (Criteria) this;
        }

        public Criteria andGene_mutationIsNull() {
            addCriterion("gene_mutation is null");
            return (Criteria) this;
        }

        public Criteria andGene_mutationIsNotNull() {
            addCriterion("gene_mutation is not null");
            return (Criteria) this;
        }

        public Criteria andGene_mutationEqualTo(String value) {
            addCriterion("gene_mutation =", value, "gene_mutation");
            return (Criteria) this;
        }

        public Criteria andGene_mutationNotEqualTo(String value) {
            addCriterion("gene_mutation <>", value, "gene_mutation");
            return (Criteria) this;
        }

        public Criteria andGene_mutationGreaterThan(String value) {
            addCriterion("gene_mutation >", value, "gene_mutation");
            return (Criteria) this;
        }

        public Criteria andGene_mutationGreaterThanOrEqualTo(String value) {
            addCriterion("gene_mutation >=", value, "gene_mutation");
            return (Criteria) this;
        }

        public Criteria andGene_mutationLessThan(String value) {
            addCriterion("gene_mutation <", value, "gene_mutation");
            return (Criteria) this;
        }

        public Criteria andGene_mutationLessThanOrEqualTo(String value) {
            addCriterion("gene_mutation <=", value, "gene_mutation");
            return (Criteria) this;
        }

        public Criteria andGene_mutationLike(String value) {
            addCriterion("gene_mutation like", value, "gene_mutation");
            return (Criteria) this;
        }

        public Criteria andGene_mutationNotLike(String value) {
            addCriterion("gene_mutation not like", value, "gene_mutation");
            return (Criteria) this;
        }

        public Criteria andGene_mutationIn(List<String> values) {
            addCriterion("gene_mutation in", values, "gene_mutation");
            return (Criteria) this;
        }

        public Criteria andGene_mutationNotIn(List<String> values) {
            addCriterion("gene_mutation not in", values, "gene_mutation");
            return (Criteria) this;
        }

        public Criteria andGene_mutationBetween(String value1, String value2) {
            addCriterion("gene_mutation between", value1, value2, "gene_mutation");
            return (Criteria) this;
        }

        public Criteria andGene_mutationNotBetween(String value1, String value2) {
            addCriterion("gene_mutation not between", value1, value2, "gene_mutation");
            return (Criteria) this;
        }

        public Criteria andGene_speciesIsNull() {
            addCriterion("gene_species is null");
            return (Criteria) this;
        }

        public Criteria andGene_speciesIsNotNull() {
            addCriterion("gene_species is not null");
            return (Criteria) this;
        }

        public Criteria andGene_speciesEqualTo(String value) {
            addCriterion("gene_species =", value, "gene_species");
            return (Criteria) this;
        }

        public Criteria andGene_speciesNotEqualTo(String value) {
            addCriterion("gene_species <>", value, "gene_species");
            return (Criteria) this;
        }

        public Criteria andGene_speciesGreaterThan(String value) {
            addCriterion("gene_species >", value, "gene_species");
            return (Criteria) this;
        }

        public Criteria andGene_speciesGreaterThanOrEqualTo(String value) {
            addCriterion("gene_species >=", value, "gene_species");
            return (Criteria) this;
        }

        public Criteria andGene_speciesLessThan(String value) {
            addCriterion("gene_species <", value, "gene_species");
            return (Criteria) this;
        }

        public Criteria andGene_speciesLessThanOrEqualTo(String value) {
            addCriterion("gene_species <=", value, "gene_species");
            return (Criteria) this;
        }

        public Criteria andGene_speciesLike(String value) {
            addCriterion("gene_species like", value, "gene_species");
            return (Criteria) this;
        }

        public Criteria andGene_speciesNotLike(String value) {
            addCriterion("gene_species not like", value, "gene_species");
            return (Criteria) this;
        }

        public Criteria andGene_speciesIn(List<String> values) {
            addCriterion("gene_species in", values, "gene_species");
            return (Criteria) this;
        }

        public Criteria andGene_speciesNotIn(List<String> values) {
            addCriterion("gene_species not in", values, "gene_species");
            return (Criteria) this;
        }

        public Criteria andGene_speciesBetween(String value1, String value2) {
            addCriterion("gene_species between", value1, value2, "gene_species");
            return (Criteria) this;
        }

        public Criteria andGene_speciesNotBetween(String value1, String value2) {
            addCriterion("gene_species not between", value1, value2, "gene_species");
            return (Criteria) this;
        }

        public Criteria andGene_sizeIsNull() {
            addCriterion("gene_size is null");
            return (Criteria) this;
        }

        public Criteria andGene_sizeIsNotNull() {
            addCriterion("gene_size is not null");
            return (Criteria) this;
        }

        public Criteria andGene_sizeEqualTo(String value) {
            addCriterion("gene_size =", value, "gene_size");
            return (Criteria) this;
        }

        public Criteria andGene_sizeNotEqualTo(String value) {
            addCriterion("gene_size <>", value, "gene_size");
            return (Criteria) this;
        }

        public Criteria andGene_sizeGreaterThan(String value) {
            addCriterion("gene_size >", value, "gene_size");
            return (Criteria) this;
        }

        public Criteria andGene_sizeGreaterThanOrEqualTo(String value) {
            addCriterion("gene_size >=", value, "gene_size");
            return (Criteria) this;
        }

        public Criteria andGene_sizeLessThan(String value) {
            addCriterion("gene_size <", value, "gene_size");
            return (Criteria) this;
        }

        public Criteria andGene_sizeLessThanOrEqualTo(String value) {
            addCriterion("gene_size <=", value, "gene_size");
            return (Criteria) this;
        }

        public Criteria andGene_sizeLike(String value) {
            addCriterion("gene_size like", value, "gene_size");
            return (Criteria) this;
        }

        public Criteria andGene_sizeNotLike(String value) {
            addCriterion("gene_size not like", value, "gene_size");
            return (Criteria) this;
        }

        public Criteria andGene_sizeIn(List<String> values) {
            addCriterion("gene_size in", values, "gene_size");
            return (Criteria) this;
        }

        public Criteria andGene_sizeNotIn(List<String> values) {
            addCriterion("gene_size not in", values, "gene_size");
            return (Criteria) this;
        }

        public Criteria andGene_sizeBetween(String value1, String value2) {
            addCriterion("gene_size between", value1, value2, "gene_size");
            return (Criteria) this;
        }

        public Criteria andGene_sizeNotBetween(String value1, String value2) {
            addCriterion("gene_size not between", value1, value2, "gene_size");
            return (Criteria) this;
        }

        public Criteria andGene_tagIsNull() {
            addCriterion("gene_tag is null");
            return (Criteria) this;
        }

        public Criteria andGene_tagIsNotNull() {
            addCriterion("gene_tag is not null");
            return (Criteria) this;
        }

        public Criteria andGene_tagEqualTo(String value) {
            addCriterion("gene_tag =", value, "gene_tag");
            return (Criteria) this;
        }

        public Criteria andGene_tagNotEqualTo(String value) {
            addCriterion("gene_tag <>", value, "gene_tag");
            return (Criteria) this;
        }

        public Criteria andGene_tagGreaterThan(String value) {
            addCriterion("gene_tag >", value, "gene_tag");
            return (Criteria) this;
        }

        public Criteria andGene_tagGreaterThanOrEqualTo(String value) {
            addCriterion("gene_tag >=", value, "gene_tag");
            return (Criteria) this;
        }

        public Criteria andGene_tagLessThan(String value) {
            addCriterion("gene_tag <", value, "gene_tag");
            return (Criteria) this;
        }

        public Criteria andGene_tagLessThanOrEqualTo(String value) {
            addCriterion("gene_tag <=", value, "gene_tag");
            return (Criteria) this;
        }

        public Criteria andGene_tagLike(String value) {
            addCriterion("gene_tag like", value, "gene_tag");
            return (Criteria) this;
        }

        public Criteria andGene_tagNotLike(String value) {
            addCriterion("gene_tag not like", value, "gene_tag");
            return (Criteria) this;
        }

        public Criteria andGene_tagIn(List<String> values) {
            addCriterion("gene_tag in", values, "gene_tag");
            return (Criteria) this;
        }

        public Criteria andGene_tagNotIn(List<String> values) {
            addCriterion("gene_tag not in", values, "gene_tag");
            return (Criteria) this;
        }

        public Criteria andGene_tagBetween(String value1, String value2) {
            addCriterion("gene_tag between", value1, value2, "gene_tag");
            return (Criteria) this;
        }

        public Criteria andGene_tagNotBetween(String value1, String value2) {
            addCriterion("gene_tag not between", value1, value2, "gene_tag");
            return (Criteria) this;
        }

        public Criteria andGene_terminalIsNull() {
            addCriterion("gene_terminal is null");
            return (Criteria) this;
        }

        public Criteria andGene_terminalIsNotNull() {
            addCriterion("gene_terminal is not null");
            return (Criteria) this;
        }

        public Criteria andGene_terminalEqualTo(String value) {
            addCriterion("gene_terminal =", value, "gene_terminal");
            return (Criteria) this;
        }

        public Criteria andGene_terminalNotEqualTo(String value) {
            addCriterion("gene_terminal <>", value, "gene_terminal");
            return (Criteria) this;
        }

        public Criteria andGene_terminalGreaterThan(String value) {
            addCriterion("gene_terminal >", value, "gene_terminal");
            return (Criteria) this;
        }

        public Criteria andGene_terminalGreaterThanOrEqualTo(String value) {
            addCriterion("gene_terminal >=", value, "gene_terminal");
            return (Criteria) this;
        }

        public Criteria andGene_terminalLessThan(String value) {
            addCriterion("gene_terminal <", value, "gene_terminal");
            return (Criteria) this;
        }

        public Criteria andGene_terminalLessThanOrEqualTo(String value) {
            addCriterion("gene_terminal <=", value, "gene_terminal");
            return (Criteria) this;
        }

        public Criteria andGene_terminalLike(String value) {
            addCriterion("gene_terminal like", value, "gene_terminal");
            return (Criteria) this;
        }

        public Criteria andGene_terminalNotLike(String value) {
            addCriterion("gene_terminal not like", value, "gene_terminal");
            return (Criteria) this;
        }

        public Criteria andGene_terminalIn(List<String> values) {
            addCriterion("gene_terminal in", values, "gene_terminal");
            return (Criteria) this;
        }

        public Criteria andGene_terminalNotIn(List<String> values) {
            addCriterion("gene_terminal not in", values, "gene_terminal");
            return (Criteria) this;
        }

        public Criteria andGene_terminalBetween(String value1, String value2) {
            addCriterion("gene_terminal between", value1, value2, "gene_terminal");
            return (Criteria) this;
        }

        public Criteria andGene_terminalNotBetween(String value1, String value2) {
            addCriterion("gene_terminal not between", value1, value2, "gene_terminal");
            return (Criteria) this;
        }

        public Criteria andVector_backboneIsNull() {
            addCriterion("vector_backbone is null");
            return (Criteria) this;
        }

        public Criteria andVector_backboneIsNotNull() {
            addCriterion("vector_backbone is not null");
            return (Criteria) this;
        }

        public Criteria andVector_backboneEqualTo(String value) {
            addCriterion("vector_backbone =", value, "vector_backbone");
            return (Criteria) this;
        }

        public Criteria andVector_backboneNotEqualTo(String value) {
            addCriterion("vector_backbone <>", value, "vector_backbone");
            return (Criteria) this;
        }

        public Criteria andVector_backboneGreaterThan(String value) {
            addCriterion("vector_backbone >", value, "vector_backbone");
            return (Criteria) this;
        }

        public Criteria andVector_backboneGreaterThanOrEqualTo(String value) {
            addCriterion("vector_backbone >=", value, "vector_backbone");
            return (Criteria) this;
        }

        public Criteria andVector_backboneLessThan(String value) {
            addCriterion("vector_backbone <", value, "vector_backbone");
            return (Criteria) this;
        }

        public Criteria andVector_backboneLessThanOrEqualTo(String value) {
            addCriterion("vector_backbone <=", value, "vector_backbone");
            return (Criteria) this;
        }

        public Criteria andVector_backboneLike(String value) {
            addCriterion("vector_backbone like", value, "vector_backbone");
            return (Criteria) this;
        }

        public Criteria andVector_backboneNotLike(String value) {
            addCriterion("vector_backbone not like", value, "vector_backbone");
            return (Criteria) this;
        }

        public Criteria andVector_backboneIn(List<String> values) {
            addCriterion("vector_backbone in", values, "vector_backbone");
            return (Criteria) this;
        }

        public Criteria andVector_backboneNotIn(List<String> values) {
            addCriterion("vector_backbone not in", values, "vector_backbone");
            return (Criteria) this;
        }

        public Criteria andVector_backboneBetween(String value1, String value2) {
            addCriterion("vector_backbone between", value1, value2, "vector_backbone");
            return (Criteria) this;
        }

        public Criteria andVector_backboneNotBetween(String value1, String value2) {
            addCriterion("vector_backbone not between", value1, value2, "vector_backbone");
            return (Criteria) this;
        }

        public Criteria andVector_backbone_manufactorIsNull() {
            addCriterion("vector_backbone_manufactor is null");
            return (Criteria) this;
        }

        public Criteria andVector_backbone_manufactorIsNotNull() {
            addCriterion("vector_backbone_manufactor is not null");
            return (Criteria) this;
        }

        public Criteria andVector_backbone_manufactorEqualTo(String value) {
            addCriterion("vector_backbone_manufactor =", value, "vector_backbone_manufactor");
            return (Criteria) this;
        }

        public Criteria andVector_backbone_manufactorNotEqualTo(String value) {
            addCriterion("vector_backbone_manufactor <>", value, "vector_backbone_manufactor");
            return (Criteria) this;
        }

        public Criteria andVector_backbone_manufactorGreaterThan(String value) {
            addCriterion("vector_backbone_manufactor >", value, "vector_backbone_manufactor");
            return (Criteria) this;
        }

        public Criteria andVector_backbone_manufactorGreaterThanOrEqualTo(String value) {
            addCriterion("vector_backbone_manufactor >=", value, "vector_backbone_manufactor");
            return (Criteria) this;
        }

        public Criteria andVector_backbone_manufactorLessThan(String value) {
            addCriterion("vector_backbone_manufactor <", value, "vector_backbone_manufactor");
            return (Criteria) this;
        }

        public Criteria andVector_backbone_manufactorLessThanOrEqualTo(String value) {
            addCriterion("vector_backbone_manufactor <=", value, "vector_backbone_manufactor");
            return (Criteria) this;
        }

        public Criteria andVector_backbone_manufactorLike(String value) {
            addCriterion("vector_backbone_manufactor like", value, "vector_backbone_manufactor");
            return (Criteria) this;
        }

        public Criteria andVector_backbone_manufactorNotLike(String value) {
            addCriterion("vector_backbone_manufactor not like", value, "vector_backbone_manufactor");
            return (Criteria) this;
        }

        public Criteria andVector_backbone_manufactorIn(List<String> values) {
            addCriterion("vector_backbone_manufactor in", values, "vector_backbone_manufactor");
            return (Criteria) this;
        }

        public Criteria andVector_backbone_manufactorNotIn(List<String> values) {
            addCriterion("vector_backbone_manufactor not in", values, "vector_backbone_manufactor");
            return (Criteria) this;
        }

        public Criteria andVector_backbone_manufactorBetween(String value1, String value2) {
            addCriterion("vector_backbone_manufactor between", value1, value2, "vector_backbone_manufactor");
            return (Criteria) this;
        }

        public Criteria andVector_backbone_manufactorNotBetween(String value1, String value2) {
            addCriterion("vector_backbone_manufactor not between", value1, value2, "vector_backbone_manufactor");
            return (Criteria) this;
        }

        public Criteria andVector_typeIsNull() {
            addCriterion("vector_type is null");
            return (Criteria) this;
        }

        public Criteria andVector_typeIsNotNull() {
            addCriterion("vector_type is not null");
            return (Criteria) this;
        }

        public Criteria andVector_typeEqualTo(String value) {
            addCriterion("vector_type =", value, "vector_type");
            return (Criteria) this;
        }

        public Criteria andVector_typeNotEqualTo(String value) {
            addCriterion("vector_type <>", value, "vector_type");
            return (Criteria) this;
        }

        public Criteria andVector_typeGreaterThan(String value) {
            addCriterion("vector_type >", value, "vector_type");
            return (Criteria) this;
        }

        public Criteria andVector_typeGreaterThanOrEqualTo(String value) {
            addCriterion("vector_type >=", value, "vector_type");
            return (Criteria) this;
        }

        public Criteria andVector_typeLessThan(String value) {
            addCriterion("vector_type <", value, "vector_type");
            return (Criteria) this;
        }

        public Criteria andVector_typeLessThanOrEqualTo(String value) {
            addCriterion("vector_type <=", value, "vector_type");
            return (Criteria) this;
        }

        public Criteria andVector_typeLike(String value) {
            addCriterion("vector_type like", value, "vector_type");
            return (Criteria) this;
        }

        public Criteria andVector_typeNotLike(String value) {
            addCriterion("vector_type not like", value, "vector_type");
            return (Criteria) this;
        }

        public Criteria andVector_typeIn(List<String> values) {
            addCriterion("vector_type in", values, "vector_type");
            return (Criteria) this;
        }

        public Criteria andVector_typeNotIn(List<String> values) {
            addCriterion("vector_type not in", values, "vector_type");
            return (Criteria) this;
        }

        public Criteria andVector_typeBetween(String value1, String value2) {
            addCriterion("vector_type between", value1, value2, "vector_type");
            return (Criteria) this;
        }

        public Criteria andVector_typeNotBetween(String value1, String value2) {
            addCriterion("vector_type not between", value1, value2, "vector_type");
            return (Criteria) this;
        }

        public Criteria andVector_backbone_sizeIsNull() {
            addCriterion("vector_backbone_size is null");
            return (Criteria) this;
        }

        public Criteria andVector_backbone_sizeIsNotNull() {
            addCriterion("vector_backbone_size is not null");
            return (Criteria) this;
        }

        public Criteria andVector_backbone_sizeEqualTo(String value) {
            addCriterion("vector_backbone_size =", value, "vector_backbone_size");
            return (Criteria) this;
        }

        public Criteria andVector_backbone_sizeNotEqualTo(String value) {
            addCriterion("vector_backbone_size <>", value, "vector_backbone_size");
            return (Criteria) this;
        }

        public Criteria andVector_backbone_sizeGreaterThan(String value) {
            addCriterion("vector_backbone_size >", value, "vector_backbone_size");
            return (Criteria) this;
        }

        public Criteria andVector_backbone_sizeGreaterThanOrEqualTo(String value) {
            addCriterion("vector_backbone_size >=", value, "vector_backbone_size");
            return (Criteria) this;
        }

        public Criteria andVector_backbone_sizeLessThan(String value) {
            addCriterion("vector_backbone_size <", value, "vector_backbone_size");
            return (Criteria) this;
        }

        public Criteria andVector_backbone_sizeLessThanOrEqualTo(String value) {
            addCriterion("vector_backbone_size <=", value, "vector_backbone_size");
            return (Criteria) this;
        }

        public Criteria andVector_backbone_sizeLike(String value) {
            addCriterion("vector_backbone_size like", value, "vector_backbone_size");
            return (Criteria) this;
        }

        public Criteria andVector_backbone_sizeNotLike(String value) {
            addCriterion("vector_backbone_size not like", value, "vector_backbone_size");
            return (Criteria) this;
        }

        public Criteria andVector_backbone_sizeIn(List<String> values) {
            addCriterion("vector_backbone_size in", values, "vector_backbone_size");
            return (Criteria) this;
        }

        public Criteria andVector_backbone_sizeNotIn(List<String> values) {
            addCriterion("vector_backbone_size not in", values, "vector_backbone_size");
            return (Criteria) this;
        }

        public Criteria andVector_backbone_sizeBetween(String value1, String value2) {
            addCriterion("vector_backbone_size between", value1, value2, "vector_backbone_size");
            return (Criteria) this;
        }

        public Criteria andVector_backbone_sizeNotBetween(String value1, String value2) {
            addCriterion("vector_backbone_size not between", value1, value2, "vector_backbone_size");
            return (Criteria) this;
        }

        public Criteria andClone_promoterIsNull() {
            addCriterion("clone_promoter is null");
            return (Criteria) this;
        }

        public Criteria andClone_promoterIsNotNull() {
            addCriterion("clone_promoter is not null");
            return (Criteria) this;
        }

        public Criteria andClone_promoterEqualTo(String value) {
            addCriterion("clone_promoter =", value, "clone_promoter");
            return (Criteria) this;
        }

        public Criteria andClone_promoterNotEqualTo(String value) {
            addCriterion("clone_promoter <>", value, "clone_promoter");
            return (Criteria) this;
        }

        public Criteria andClone_promoterGreaterThan(String value) {
            addCriterion("clone_promoter >", value, "clone_promoter");
            return (Criteria) this;
        }

        public Criteria andClone_promoterGreaterThanOrEqualTo(String value) {
            addCriterion("clone_promoter >=", value, "clone_promoter");
            return (Criteria) this;
        }

        public Criteria andClone_promoterLessThan(String value) {
            addCriterion("clone_promoter <", value, "clone_promoter");
            return (Criteria) this;
        }

        public Criteria andClone_promoterLessThanOrEqualTo(String value) {
            addCriterion("clone_promoter <=", value, "clone_promoter");
            return (Criteria) this;
        }

        public Criteria andClone_promoterLike(String value) {
            addCriterion("clone_promoter like", value, "clone_promoter");
            return (Criteria) this;
        }

        public Criteria andClone_promoterNotLike(String value) {
            addCriterion("clone_promoter not like", value, "clone_promoter");
            return (Criteria) this;
        }

        public Criteria andClone_promoterIn(List<String> values) {
            addCriterion("clone_promoter in", values, "clone_promoter");
            return (Criteria) this;
        }

        public Criteria andClone_promoterNotIn(List<String> values) {
            addCriterion("clone_promoter not in", values, "clone_promoter");
            return (Criteria) this;
        }

        public Criteria andClone_promoterBetween(String value1, String value2) {
            addCriterion("clone_promoter between", value1, value2, "clone_promoter");
            return (Criteria) this;
        }

        public Criteria andClone_promoterNotBetween(String value1, String value2) {
            addCriterion("clone_promoter not between", value1, value2, "clone_promoter");
            return (Criteria) this;
        }

        public Criteria andClone_methodIsNull() {
            addCriterion("clone_method is null");
            return (Criteria) this;
        }

        public Criteria andClone_methodIsNotNull() {
            addCriterion("clone_method is not null");
            return (Criteria) this;
        }

        public Criteria andClone_methodEqualTo(String value) {
            addCriterion("clone_method =", value, "clone_method");
            return (Criteria) this;
        }

        public Criteria andClone_methodNotEqualTo(String value) {
            addCriterion("clone_method <>", value, "clone_method");
            return (Criteria) this;
        }

        public Criteria andClone_methodGreaterThan(String value) {
            addCriterion("clone_method >", value, "clone_method");
            return (Criteria) this;
        }

        public Criteria andClone_methodGreaterThanOrEqualTo(String value) {
            addCriterion("clone_method >=", value, "clone_method");
            return (Criteria) this;
        }

        public Criteria andClone_methodLessThan(String value) {
            addCriterion("clone_method <", value, "clone_method");
            return (Criteria) this;
        }

        public Criteria andClone_methodLessThanOrEqualTo(String value) {
            addCriterion("clone_method <=", value, "clone_method");
            return (Criteria) this;
        }

        public Criteria andClone_methodLike(String value) {
            addCriterion("clone_method like", value, "clone_method");
            return (Criteria) this;
        }

        public Criteria andClone_methodNotLike(String value) {
            addCriterion("clone_method not like", value, "clone_method");
            return (Criteria) this;
        }

        public Criteria andClone_methodIn(List<String> values) {
            addCriterion("clone_method in", values, "clone_method");
            return (Criteria) this;
        }

        public Criteria andClone_methodNotIn(List<String> values) {
            addCriterion("clone_method not in", values, "clone_method");
            return (Criteria) this;
        }

        public Criteria andClone_methodBetween(String value1, String value2) {
            addCriterion("clone_method between", value1, value2, "clone_method");
            return (Criteria) this;
        }

        public Criteria andClone_methodNotBetween(String value1, String value2) {
            addCriterion("clone_method not between", value1, value2, "clone_method");
            return (Criteria) this;
        }

        public Criteria andClone_siteIsNull() {
            addCriterion("clone_site is null");
            return (Criteria) this;
        }

        public Criteria andClone_siteIsNotNull() {
            addCriterion("clone_site is not null");
            return (Criteria) this;
        }

        public Criteria andClone_siteEqualTo(String value) {
            addCriterion("clone_site =", value, "clone_site");
            return (Criteria) this;
        }

        public Criteria andClone_siteNotEqualTo(String value) {
            addCriterion("clone_site <>", value, "clone_site");
            return (Criteria) this;
        }

        public Criteria andClone_siteGreaterThan(String value) {
            addCriterion("clone_site >", value, "clone_site");
            return (Criteria) this;
        }

        public Criteria andClone_siteGreaterThanOrEqualTo(String value) {
            addCriterion("clone_site >=", value, "clone_site");
            return (Criteria) this;
        }

        public Criteria andClone_siteLessThan(String value) {
            addCriterion("clone_site <", value, "clone_site");
            return (Criteria) this;
        }

        public Criteria andClone_siteLessThanOrEqualTo(String value) {
            addCriterion("clone_site <=", value, "clone_site");
            return (Criteria) this;
        }

        public Criteria andClone_siteLike(String value) {
            addCriterion("clone_site like", value, "clone_site");
            return (Criteria) this;
        }

        public Criteria andClone_siteNotLike(String value) {
            addCriterion("clone_site not like", value, "clone_site");
            return (Criteria) this;
        }

        public Criteria andClone_siteIn(List<String> values) {
            addCriterion("clone_site in", values, "clone_site");
            return (Criteria) this;
        }

        public Criteria andClone_siteNotIn(List<String> values) {
            addCriterion("clone_site not in", values, "clone_site");
            return (Criteria) this;
        }

        public Criteria andClone_siteBetween(String value1, String value2) {
            addCriterion("clone_site between", value1, value2, "clone_site");
            return (Criteria) this;
        }

        public Criteria andClone_siteNotBetween(String value1, String value2) {
            addCriterion("clone_site not between", value1, value2, "clone_site");
            return (Criteria) this;
        }

        public Criteria andClone_sequence_primerIsNull() {
            addCriterion("clone_sequence_primer is null");
            return (Criteria) this;
        }

        public Criteria andClone_sequence_primerIsNotNull() {
            addCriterion("clone_sequence_primer is not null");
            return (Criteria) this;
        }

        public Criteria andClone_sequence_primerEqualTo(String value) {
            addCriterion("clone_sequence_primer =", value, "clone_sequence_primer");
            return (Criteria) this;
        }

        public Criteria andClone_sequence_primerNotEqualTo(String value) {
            addCriterion("clone_sequence_primer <>", value, "clone_sequence_primer");
            return (Criteria) this;
        }

        public Criteria andClone_sequence_primerGreaterThan(String value) {
            addCriterion("clone_sequence_primer >", value, "clone_sequence_primer");
            return (Criteria) this;
        }

        public Criteria andClone_sequence_primerGreaterThanOrEqualTo(String value) {
            addCriterion("clone_sequence_primer >=", value, "clone_sequence_primer");
            return (Criteria) this;
        }

        public Criteria andClone_sequence_primerLessThan(String value) {
            addCriterion("clone_sequence_primer <", value, "clone_sequence_primer");
            return (Criteria) this;
        }

        public Criteria andClone_sequence_primerLessThanOrEqualTo(String value) {
            addCriterion("clone_sequence_primer <=", value, "clone_sequence_primer");
            return (Criteria) this;
        }

        public Criteria andClone_sequence_primerLike(String value) {
            addCriterion("clone_sequence_primer like", value, "clone_sequence_primer");
            return (Criteria) this;
        }

        public Criteria andClone_sequence_primerNotLike(String value) {
            addCriterion("clone_sequence_primer not like", value, "clone_sequence_primer");
            return (Criteria) this;
        }

        public Criteria andClone_sequence_primerIn(List<String> values) {
            addCriterion("clone_sequence_primer in", values, "clone_sequence_primer");
            return (Criteria) this;
        }

        public Criteria andClone_sequence_primerNotIn(List<String> values) {
            addCriterion("clone_sequence_primer not in", values, "clone_sequence_primer");
            return (Criteria) this;
        }

        public Criteria andClone_sequence_primerBetween(String value1, String value2) {
            addCriterion("clone_sequence_primer between", value1, value2, "clone_sequence_primer");
            return (Criteria) this;
        }

        public Criteria andClone_sequence_primerNotBetween(String value1, String value2) {
            addCriterion("clone_sequence_primer not between", value1, value2, "clone_sequence_primer");
            return (Criteria) this;
        }

        public Criteria andGrowth_bacterial_resistanceIsNull() {
            addCriterion("growth_bacterial_resistance is null");
            return (Criteria) this;
        }

        public Criteria andGrowth_bacterial_resistanceIsNotNull() {
            addCriterion("growth_bacterial_resistance is not null");
            return (Criteria) this;
        }

        public Criteria andGrowth_bacterial_resistanceEqualTo(String value) {
            addCriterion("growth_bacterial_resistance =", value, "growth_bacterial_resistance");
            return (Criteria) this;
        }

        public Criteria andGrowth_bacterial_resistanceNotEqualTo(String value) {
            addCriterion("growth_bacterial_resistance <>", value, "growth_bacterial_resistance");
            return (Criteria) this;
        }

        public Criteria andGrowth_bacterial_resistanceGreaterThan(String value) {
            addCriterion("growth_bacterial_resistance >", value, "growth_bacterial_resistance");
            return (Criteria) this;
        }

        public Criteria andGrowth_bacterial_resistanceGreaterThanOrEqualTo(String value) {
            addCriterion("growth_bacterial_resistance >=", value, "growth_bacterial_resistance");
            return (Criteria) this;
        }

        public Criteria andGrowth_bacterial_resistanceLessThan(String value) {
            addCriterion("growth_bacterial_resistance <", value, "growth_bacterial_resistance");
            return (Criteria) this;
        }

        public Criteria andGrowth_bacterial_resistanceLessThanOrEqualTo(String value) {
            addCriterion("growth_bacterial_resistance <=", value, "growth_bacterial_resistance");
            return (Criteria) this;
        }

        public Criteria andGrowth_bacterial_resistanceLike(String value) {
            addCriterion("growth_bacterial_resistance like", value, "growth_bacterial_resistance");
            return (Criteria) this;
        }

        public Criteria andGrowth_bacterial_resistanceNotLike(String value) {
            addCriterion("growth_bacterial_resistance not like", value, "growth_bacterial_resistance");
            return (Criteria) this;
        }

        public Criteria andGrowth_bacterial_resistanceIn(List<String> values) {
            addCriterion("growth_bacterial_resistance in", values, "growth_bacterial_resistance");
            return (Criteria) this;
        }

        public Criteria andGrowth_bacterial_resistanceNotIn(List<String> values) {
            addCriterion("growth_bacterial_resistance not in", values, "growth_bacterial_resistance");
            return (Criteria) this;
        }

        public Criteria andGrowth_bacterial_resistanceBetween(String value1, String value2) {
            addCriterion("growth_bacterial_resistance between", value1, value2, "growth_bacterial_resistance");
            return (Criteria) this;
        }

        public Criteria andGrowth_bacterial_resistanceNotBetween(String value1, String value2) {
            addCriterion("growth_bacterial_resistance not between", value1, value2, "growth_bacterial_resistance");
            return (Criteria) this;
        }

        public Criteria andGrowth_strainIsNull() {
            addCriterion("growth_strain is null");
            return (Criteria) this;
        }

        public Criteria andGrowth_strainIsNotNull() {
            addCriterion("growth_strain is not null");
            return (Criteria) this;
        }

        public Criteria andGrowth_strainEqualTo(String value) {
            addCriterion("growth_strain =", value, "growth_strain");
            return (Criteria) this;
        }

        public Criteria andGrowth_strainNotEqualTo(String value) {
            addCriterion("growth_strain <>", value, "growth_strain");
            return (Criteria) this;
        }

        public Criteria andGrowth_strainGreaterThan(String value) {
            addCriterion("growth_strain >", value, "growth_strain");
            return (Criteria) this;
        }

        public Criteria andGrowth_strainGreaterThanOrEqualTo(String value) {
            addCriterion("growth_strain >=", value, "growth_strain");
            return (Criteria) this;
        }

        public Criteria andGrowth_strainLessThan(String value) {
            addCriterion("growth_strain <", value, "growth_strain");
            return (Criteria) this;
        }

        public Criteria andGrowth_strainLessThanOrEqualTo(String value) {
            addCriterion("growth_strain <=", value, "growth_strain");
            return (Criteria) this;
        }

        public Criteria andGrowth_strainLike(String value) {
            addCriterion("growth_strain like", value, "growth_strain");
            return (Criteria) this;
        }

        public Criteria andGrowth_strainNotLike(String value) {
            addCriterion("growth_strain not like", value, "growth_strain");
            return (Criteria) this;
        }

        public Criteria andGrowth_strainIn(List<String> values) {
            addCriterion("growth_strain in", values, "growth_strain");
            return (Criteria) this;
        }

        public Criteria andGrowth_strainNotIn(List<String> values) {
            addCriterion("growth_strain not in", values, "growth_strain");
            return (Criteria) this;
        }

        public Criteria andGrowth_strainBetween(String value1, String value2) {
            addCriterion("growth_strain between", value1, value2, "growth_strain");
            return (Criteria) this;
        }

        public Criteria andGrowth_strainNotBetween(String value1, String value2) {
            addCriterion("growth_strain not between", value1, value2, "growth_strain");
            return (Criteria) this;
        }

        public Criteria andGrowth_copy_numberIsNull() {
            addCriterion("growth_copy_number is null");
            return (Criteria) this;
        }

        public Criteria andGrowth_copy_numberIsNotNull() {
            addCriterion("growth_copy_number is not null");
            return (Criteria) this;
        }

        public Criteria andGrowth_copy_numberEqualTo(String value) {
            addCriterion("growth_copy_number =", value, "growth_copy_number");
            return (Criteria) this;
        }

        public Criteria andGrowth_copy_numberNotEqualTo(String value) {
            addCriterion("growth_copy_number <>", value, "growth_copy_number");
            return (Criteria) this;
        }

        public Criteria andGrowth_copy_numberGreaterThan(String value) {
            addCriterion("growth_copy_number >", value, "growth_copy_number");
            return (Criteria) this;
        }

        public Criteria andGrowth_copy_numberGreaterThanOrEqualTo(String value) {
            addCriterion("growth_copy_number >=", value, "growth_copy_number");
            return (Criteria) this;
        }

        public Criteria andGrowth_copy_numberLessThan(String value) {
            addCriterion("growth_copy_number <", value, "growth_copy_number");
            return (Criteria) this;
        }

        public Criteria andGrowth_copy_numberLessThanOrEqualTo(String value) {
            addCriterion("growth_copy_number <=", value, "growth_copy_number");
            return (Criteria) this;
        }

        public Criteria andGrowth_copy_numberLike(String value) {
            addCriterion("growth_copy_number like", value, "growth_copy_number");
            return (Criteria) this;
        }

        public Criteria andGrowth_copy_numberNotLike(String value) {
            addCriterion("growth_copy_number not like", value, "growth_copy_number");
            return (Criteria) this;
        }

        public Criteria andGrowth_copy_numberIn(List<String> values) {
            addCriterion("growth_copy_number in", values, "growth_copy_number");
            return (Criteria) this;
        }

        public Criteria andGrowth_copy_numberNotIn(List<String> values) {
            addCriterion("growth_copy_number not in", values, "growth_copy_number");
            return (Criteria) this;
        }

        public Criteria andGrowth_copy_numberBetween(String value1, String value2) {
            addCriterion("growth_copy_number between", value1, value2, "growth_copy_number");
            return (Criteria) this;
        }

        public Criteria andGrowth_copy_numberNotBetween(String value1, String value2) {
            addCriterion("growth_copy_number not between", value1, value2, "growth_copy_number");
            return (Criteria) this;
        }

        public Criteria andGrowth_temperatureIsNull() {
            addCriterion("growth_temperature is null");
            return (Criteria) this;
        }

        public Criteria andGrowth_temperatureIsNotNull() {
            addCriterion("growth_temperature is not null");
            return (Criteria) this;
        }

        public Criteria andGrowth_temperatureEqualTo(String value) {
            addCriterion("growth_temperature =", value, "growth_temperature");
            return (Criteria) this;
        }

        public Criteria andGrowth_temperatureNotEqualTo(String value) {
            addCriterion("growth_temperature <>", value, "growth_temperature");
            return (Criteria) this;
        }

        public Criteria andGrowth_temperatureGreaterThan(String value) {
            addCriterion("growth_temperature >", value, "growth_temperature");
            return (Criteria) this;
        }

        public Criteria andGrowth_temperatureGreaterThanOrEqualTo(String value) {
            addCriterion("growth_temperature >=", value, "growth_temperature");
            return (Criteria) this;
        }

        public Criteria andGrowth_temperatureLessThan(String value) {
            addCriterion("growth_temperature <", value, "growth_temperature");
            return (Criteria) this;
        }

        public Criteria andGrowth_temperatureLessThanOrEqualTo(String value) {
            addCriterion("growth_temperature <=", value, "growth_temperature");
            return (Criteria) this;
        }

        public Criteria andGrowth_temperatureLike(String value) {
            addCriterion("growth_temperature like", value, "growth_temperature");
            return (Criteria) this;
        }

        public Criteria andGrowth_temperatureNotLike(String value) {
            addCriterion("growth_temperature not like", value, "growth_temperature");
            return (Criteria) this;
        }

        public Criteria andGrowth_temperatureIn(List<String> values) {
            addCriterion("growth_temperature in", values, "growth_temperature");
            return (Criteria) this;
        }

        public Criteria andGrowth_temperatureNotIn(List<String> values) {
            addCriterion("growth_temperature not in", values, "growth_temperature");
            return (Criteria) this;
        }

        public Criteria andGrowth_temperatureBetween(String value1, String value2) {
            addCriterion("growth_temperature between", value1, value2, "growth_temperature");
            return (Criteria) this;
        }

        public Criteria andGrowth_temperatureNotBetween(String value1, String value2) {
            addCriterion("growth_temperature not between", value1, value2, "growth_temperature");
            return (Criteria) this;
        }

        public Criteria andGrowth_selection_markIsNull() {
            addCriterion("growth_selection_mark is null");
            return (Criteria) this;
        }

        public Criteria andGrowth_selection_markIsNotNull() {
            addCriterion("growth_selection_mark is not null");
            return (Criteria) this;
        }

        public Criteria andGrowth_selection_markEqualTo(String value) {
            addCriterion("growth_selection_mark =", value, "growth_selection_mark");
            return (Criteria) this;
        }

        public Criteria andGrowth_selection_markNotEqualTo(String value) {
            addCriterion("growth_selection_mark <>", value, "growth_selection_mark");
            return (Criteria) this;
        }

        public Criteria andGrowth_selection_markGreaterThan(String value) {
            addCriterion("growth_selection_mark >", value, "growth_selection_mark");
            return (Criteria) this;
        }

        public Criteria andGrowth_selection_markGreaterThanOrEqualTo(String value) {
            addCriterion("growth_selection_mark >=", value, "growth_selection_mark");
            return (Criteria) this;
        }

        public Criteria andGrowth_selection_markLessThan(String value) {
            addCriterion("growth_selection_mark <", value, "growth_selection_mark");
            return (Criteria) this;
        }

        public Criteria andGrowth_selection_markLessThanOrEqualTo(String value) {
            addCriterion("growth_selection_mark <=", value, "growth_selection_mark");
            return (Criteria) this;
        }

        public Criteria andGrowth_selection_markLike(String value) {
            addCriterion("growth_selection_mark like", value, "growth_selection_mark");
            return (Criteria) this;
        }

        public Criteria andGrowth_selection_markNotLike(String value) {
            addCriterion("growth_selection_mark not like", value, "growth_selection_mark");
            return (Criteria) this;
        }

        public Criteria andGrowth_selection_markIn(List<String> values) {
            addCriterion("growth_selection_mark in", values, "growth_selection_mark");
            return (Criteria) this;
        }

        public Criteria andGrowth_selection_markNotIn(List<String> values) {
            addCriterion("growth_selection_mark not in", values, "growth_selection_mark");
            return (Criteria) this;
        }

        public Criteria andGrowth_selection_markBetween(String value1, String value2) {
            addCriterion("growth_selection_mark between", value1, value2, "growth_selection_mark");
            return (Criteria) this;
        }

        public Criteria andGrowth_selection_markNotBetween(String value1, String value2) {
            addCriterion("growth_selection_mark not between", value1, value2, "growth_selection_mark");
            return (Criteria) this;
        }

        public Criteria andAtt_urlsIsNull() {
            addCriterion("att_urls is null");
            return (Criteria) this;
        }

        public Criteria andAtt_urlsIsNotNull() {
            addCriterion("att_urls is not null");
            return (Criteria) this;
        }

        public Criteria andAtt_urlsEqualTo(String value) {
            addCriterion("att_urls =", value, "att_urls");
            return (Criteria) this;
        }

        public Criteria andAtt_urlsNotEqualTo(String value) {
            addCriterion("att_urls <>", value, "att_urls");
            return (Criteria) this;
        }

        public Criteria andAtt_urlsGreaterThan(String value) {
            addCriterion("att_urls >", value, "att_urls");
            return (Criteria) this;
        }

        public Criteria andAtt_urlsGreaterThanOrEqualTo(String value) {
            addCriterion("att_urls >=", value, "att_urls");
            return (Criteria) this;
        }

        public Criteria andAtt_urlsLessThan(String value) {
            addCriterion("att_urls <", value, "att_urls");
            return (Criteria) this;
        }

        public Criteria andAtt_urlsLessThanOrEqualTo(String value) {
            addCriterion("att_urls <=", value, "att_urls");
            return (Criteria) this;
        }

        public Criteria andAtt_urlsLike(String value) {
            addCriterion("att_urls like", value, "att_urls");
            return (Criteria) this;
        }

        public Criteria andAtt_urlsNotLike(String value) {
            addCriterion("att_urls not like", value, "att_urls");
            return (Criteria) this;
        }

        public Criteria andAtt_urlsIn(List<String> values) {
            addCriterion("att_urls in", values, "att_urls");
            return (Criteria) this;
        }

        public Criteria andAtt_urlsNotIn(List<String> values) {
            addCriterion("att_urls not in", values, "att_urls");
            return (Criteria) this;
        }

        public Criteria andAtt_urlsBetween(String value1, String value2) {
            addCriterion("att_urls between", value1, value2, "att_urls");
            return (Criteria) this;
        }

        public Criteria andAtt_urlsNotBetween(String value1, String value2) {
            addCriterion("att_urls not between", value1, value2, "att_urls");
            return (Criteria) this;
        }

        public Criteria andDeposit_idIsNull() {
            addCriterion("deposit_id is null");
            return (Criteria) this;
        }

        public Criteria andDeposit_idIsNotNull() {
            addCriterion("deposit_id is not null");
            return (Criteria) this;
        }

        public Criteria andDeposit_idEqualTo(Integer value) {
            addCriterion("deposit_id =", value, "deposit_id");
            return (Criteria) this;
        }

        public Criteria andDeposit_idNotEqualTo(Integer value) {
            addCriterion("deposit_id <>", value, "deposit_id");
            return (Criteria) this;
        }

        public Criteria andDeposit_idGreaterThan(Integer value) {
            addCriterion("deposit_id >", value, "deposit_id");
            return (Criteria) this;
        }

        public Criteria andDeposit_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("deposit_id >=", value, "deposit_id");
            return (Criteria) this;
        }

        public Criteria andDeposit_idLessThan(Integer value) {
            addCriterion("deposit_id <", value, "deposit_id");
            return (Criteria) this;
        }

        public Criteria andDeposit_idLessThanOrEqualTo(Integer value) {
            addCriterion("deposit_id <=", value, "deposit_id");
            return (Criteria) this;
        }

        public Criteria andDeposit_idIn(List<Integer> values) {
            addCriterion("deposit_id in", values, "deposit_id");
            return (Criteria) this;
        }

        public Criteria andDeposit_idNotIn(List<Integer> values) {
            addCriterion("deposit_id not in", values, "deposit_id");
            return (Criteria) this;
        }

        public Criteria andDeposit_idBetween(Integer value1, Integer value2) {
            addCriterion("deposit_id between", value1, value2, "deposit_id");
            return (Criteria) this;
        }

        public Criteria andDeposit_idNotBetween(Integer value1, Integer value2) {
            addCriterion("deposit_id not between", value1, value2, "deposit_id");
            return (Criteria) this;
        }

        public Criteria andVector_modificationsIsNull() {
            addCriterion("vector_modifications is null");
            return (Criteria) this;
        }

        public Criteria andVector_modificationsIsNotNull() {
            addCriterion("vector_modifications is not null");
            return (Criteria) this;
        }

        public Criteria andVector_modificationsEqualTo(String value) {
            addCriterion("vector_modifications =", value, "vector_modifications");
            return (Criteria) this;
        }

        public Criteria andVector_modificationsNotEqualTo(String value) {
            addCriterion("vector_modifications <>", value, "vector_modifications");
            return (Criteria) this;
        }

        public Criteria andVector_modificationsGreaterThan(String value) {
            addCriterion("vector_modifications >", value, "vector_modifications");
            return (Criteria) this;
        }

        public Criteria andVector_modificationsGreaterThanOrEqualTo(String value) {
            addCriterion("vector_modifications >=", value, "vector_modifications");
            return (Criteria) this;
        }

        public Criteria andVector_modificationsLessThan(String value) {
            addCriterion("vector_modifications <", value, "vector_modifications");
            return (Criteria) this;
        }

        public Criteria andVector_modificationsLessThanOrEqualTo(String value) {
            addCriterion("vector_modifications <=", value, "vector_modifications");
            return (Criteria) this;
        }

        public Criteria andVector_modificationsLike(String value) {
            addCriterion("vector_modifications like", value, "vector_modifications");
            return (Criteria) this;
        }

        public Criteria andVector_modificationsNotLike(String value) {
            addCriterion("vector_modifications not like", value, "vector_modifications");
            return (Criteria) this;
        }

        public Criteria andVector_modificationsIn(List<String> values) {
            addCriterion("vector_modifications in", values, "vector_modifications");
            return (Criteria) this;
        }

        public Criteria andVector_modificationsNotIn(List<String> values) {
            addCriterion("vector_modifications not in", values, "vector_modifications");
            return (Criteria) this;
        }

        public Criteria andVector_modificationsBetween(String value1, String value2) {
            addCriterion("vector_modifications between", value1, value2, "vector_modifications");
            return (Criteria) this;
        }

        public Criteria andVector_modificationsNotBetween(String value1, String value2) {
            addCriterion("vector_modifications not between", value1, value2, "vector_modifications");
            return (Criteria) this;
        }

        public Criteria andGoods_idIsNull() {
            addCriterion("goods_id is null");
            return (Criteria) this;
        }

        public Criteria andGoods_idIsNotNull() {
            addCriterion("goods_id is not null");
            return (Criteria) this;
        }

        public Criteria andGoods_idEqualTo(Integer value) {
            addCriterion("goods_id =", value, "goods_id");
            return (Criteria) this;
        }

        public Criteria andGoods_idNotEqualTo(Integer value) {
            addCriterion("goods_id <>", value, "goods_id");
            return (Criteria) this;
        }

        public Criteria andGoods_idGreaterThan(Integer value) {
            addCriterion("goods_id >", value, "goods_id");
            return (Criteria) this;
        }

        public Criteria andGoods_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("goods_id >=", value, "goods_id");
            return (Criteria) this;
        }

        public Criteria andGoods_idLessThan(Integer value) {
            addCriterion("goods_id <", value, "goods_id");
            return (Criteria) this;
        }

        public Criteria andGoods_idLessThanOrEqualTo(Integer value) {
            addCriterion("goods_id <=", value, "goods_id");
            return (Criteria) this;
        }

        public Criteria andGoods_idIn(List<Integer> values) {
            addCriterion("goods_id in", values, "goods_id");
            return (Criteria) this;
        }

        public Criteria andGoods_idNotIn(List<Integer> values) {
            addCriterion("goods_id not in", values, "goods_id");
            return (Criteria) this;
        }

        public Criteria andGoods_idBetween(Integer value1, Integer value2) {
            addCriterion("goods_id between", value1, value2, "goods_id");
            return (Criteria) this;
        }

        public Criteria andGoods_idNotBetween(Integer value1, Integer value2) {
            addCriterion("goods_id not between", value1, value2, "goods_id");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_plasmid_info
     *
     * @mbg.generated do_not_delete_during_merge Wed Dec 18 15:54:37 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_plasmid_info
     *
     * @mbg.generated Wed Dec 18 15:54:37 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}