package com.genetech.bean;

public class PlasmidDict {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_dict.id
     *
     * @mbg.generated Wed Apr 29 13:18:31 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_dict.plasmid_type
     *
     * @mbg.generated Wed Apr 29 13:18:31 CST 2020
     */
    private String plasmid_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_dict.gene_species
     *
     * @mbg.generated Wed Apr 29 13:18:31 CST 2020
     */
    private String gene_species;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_dict.vector_type
     *
     * @mbg.generated Wed Apr 29 13:18:31 CST 2020
     */
    private String vector_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_dict.growth_bacterial_resistance
     *
     * @mbg.generated Wed Apr 29 13:18:31 CST 2020
     */
    private String growth_bacterial_resistance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_dict.plasmid_type_other
     *
     * @mbg.generated Wed Apr 29 13:18:31 CST 2020
     */
    private String plasmid_type_other;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_dict.gene_species_other
     *
     * @mbg.generated Wed Apr 29 13:18:31 CST 2020
     */
    private String gene_species_other;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_dict.vector_type_other
     *
     * @mbg.generated Wed Apr 29 13:18:31 CST 2020
     */
    private String vector_type_other;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_dict.growth_bacterial_resistance_other
     *
     * @mbg.generated Wed Apr 29 13:18:31 CST 2020
     */
    private String growth_bacterial_resistance_other;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_dict.id
     *
     * @return the value of t_plasmid_dict.id
     *
     * @mbg.generated Wed Apr 29 13:18:31 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_dict.id
     *
     * @param id the value for t_plasmid_dict.id
     *
     * @mbg.generated Wed Apr 29 13:18:31 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_dict.plasmid_type
     *
     * @return the value of t_plasmid_dict.plasmid_type
     *
     * @mbg.generated Wed Apr 29 13:18:31 CST 2020
     */
    public String getPlasmid_type() {
        return plasmid_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_dict.plasmid_type
     *
     * @param plasmid_type the value for t_plasmid_dict.plasmid_type
     *
     * @mbg.generated Wed Apr 29 13:18:31 CST 2020
     */
    public void setPlasmid_type(String plasmid_type) {
        this.plasmid_type = plasmid_type == null ? null : plasmid_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_dict.gene_species
     *
     * @return the value of t_plasmid_dict.gene_species
     *
     * @mbg.generated Wed Apr 29 13:18:31 CST 2020
     */
    public String getGene_species() {
        return gene_species;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_dict.gene_species
     *
     * @param gene_species the value for t_plasmid_dict.gene_species
     *
     * @mbg.generated Wed Apr 29 13:18:31 CST 2020
     */
    public void setGene_species(String gene_species) {
        this.gene_species = gene_species == null ? null : gene_species.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_dict.vector_type
     *
     * @return the value of t_plasmid_dict.vector_type
     *
     * @mbg.generated Wed Apr 29 13:18:31 CST 2020
     */
    public String getVector_type() {
        return vector_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_dict.vector_type
     *
     * @param vector_type the value for t_plasmid_dict.vector_type
     *
     * @mbg.generated Wed Apr 29 13:18:31 CST 2020
     */
    public void setVector_type(String vector_type) {
        this.vector_type = vector_type == null ? null : vector_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_dict.growth_bacterial_resistance
     *
     * @return the value of t_plasmid_dict.growth_bacterial_resistance
     *
     * @mbg.generated Wed Apr 29 13:18:31 CST 2020
     */
    public String getGrowth_bacterial_resistance() {
        return growth_bacterial_resistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_dict.growth_bacterial_resistance
     *
     * @param growth_bacterial_resistance the value for t_plasmid_dict.growth_bacterial_resistance
     *
     * @mbg.generated Wed Apr 29 13:18:31 CST 2020
     */
    public void setGrowth_bacterial_resistance(String growth_bacterial_resistance) {
        this.growth_bacterial_resistance = growth_bacterial_resistance == null ? null : growth_bacterial_resistance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_dict.plasmid_type_other
     *
     * @return the value of t_plasmid_dict.plasmid_type_other
     *
     * @mbg.generated Wed Apr 29 13:18:31 CST 2020
     */
    public String getPlasmid_type_other() {
        return plasmid_type_other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_dict.plasmid_type_other
     *
     * @param plasmid_type_other the value for t_plasmid_dict.plasmid_type_other
     *
     * @mbg.generated Wed Apr 29 13:18:31 CST 2020
     */
    public void setPlasmid_type_other(String plasmid_type_other) {
        this.plasmid_type_other = plasmid_type_other == null ? null : plasmid_type_other.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_dict.gene_species_other
     *
     * @return the value of t_plasmid_dict.gene_species_other
     *
     * @mbg.generated Wed Apr 29 13:18:31 CST 2020
     */
    public String getGene_species_other() {
        return gene_species_other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_dict.gene_species_other
     *
     * @param gene_species_other the value for t_plasmid_dict.gene_species_other
     *
     * @mbg.generated Wed Apr 29 13:18:31 CST 2020
     */
    public void setGene_species_other(String gene_species_other) {
        this.gene_species_other = gene_species_other == null ? null : gene_species_other.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_dict.vector_type_other
     *
     * @return the value of t_plasmid_dict.vector_type_other
     *
     * @mbg.generated Wed Apr 29 13:18:31 CST 2020
     */
    public String getVector_type_other() {
        return vector_type_other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_dict.vector_type_other
     *
     * @param vector_type_other the value for t_plasmid_dict.vector_type_other
     *
     * @mbg.generated Wed Apr 29 13:18:31 CST 2020
     */
    public void setVector_type_other(String vector_type_other) {
        this.vector_type_other = vector_type_other == null ? null : vector_type_other.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_dict.growth_bacterial_resistance_other
     *
     * @return the value of t_plasmid_dict.growth_bacterial_resistance_other
     *
     * @mbg.generated Wed Apr 29 13:18:31 CST 2020
     */
    public String getGrowth_bacterial_resistance_other() {
        return growth_bacterial_resistance_other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_dict.growth_bacterial_resistance_other
     *
     * @param growth_bacterial_resistance_other the value for t_plasmid_dict.growth_bacterial_resistance_other
     *
     * @mbg.generated Wed Apr 29 13:18:31 CST 2020
     */
    public void setGrowth_bacterial_resistance_other(String growth_bacterial_resistance_other) {
        this.growth_bacterial_resistance_other = growth_bacterial_resistance_other == null ? null : growth_bacterial_resistance_other.trim();
    }
}