package com.genetech.bean;

import java.util.Date;

public class PlasmidInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_info.id
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_info.plasmid_identification
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    private String plasmid_identification;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_info.plasmid_name
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    private String plasmid_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_info.plasmid_name_client
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    private String plasmid_name_client;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_info.plasmid_size
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    private String plasmid_size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_info.lab_name
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    private String lab_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_info.plasmid_type
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    private String plasmid_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_info.plasmid_user_restriction
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    private String plasmid_user_restriction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_info.plasmid_submit_type
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    private String plasmid_submit_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_info.plasmid_sequence
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    private String plasmid_sequence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_info.plasmid_manufacturer
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    private String plasmid_manufacturer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_info.gene_name
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    private String gene_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_info.gene_alias
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    private String gene_alias;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_info.gene_identification
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    private String gene_identification;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_info.gene_mutation
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    private String gene_mutation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_info.gene_species
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    private String gene_species;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_info.gene_size
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    private String gene_size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_info.gene_tag
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    private String gene_tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_info.gene_terminal
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    private String gene_terminal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_info.vector_backbone
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    private String vector_backbone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_info.vector_backbone_manufactor
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    private String vector_backbone_manufactor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_info.vector_backbone_size
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    private String vector_backbone_size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_info.clone_promoter
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    private String clone_promoter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_info.clone_method
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    private String clone_method;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_info.clone_site
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    private String clone_site;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_info.clone_sequence_primer
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    private String clone_sequence_primer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_info.clone_sequence_primer_reverse
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    private String clone_sequence_primer_reverse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_info.growth_bacterial_resistance
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    private String growth_bacterial_resistance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_info.growth_strain
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    private String growth_strain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_info.growth_copy_number
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    private String growth_copy_number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_info.growth_temperature
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    private String growth_temperature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_info.growth_selection_mark
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    private String growth_selection_mark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_info.sequence_part_one
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    private String sequence_part_one;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_info.sequence_part_one_description
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    private String sequence_part_one_description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_info.sequence_part_two
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    private String sequence_part_two;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_info.sequence_part_two_description
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    private String sequence_part_two_description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_info.att_urls
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    private String att_urls;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_info.vector_modifications
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    private String vector_modifications;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_info.gene_link
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    private String gene_link;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_info.add_time
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    private Date add_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_info.source_article
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    private String source_article;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_info.plasmid_description
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    private String plasmid_description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_info.gene_description
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    private String gene_description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_info.vector_type
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    private String vector_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_info.growth_comment
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    private String growth_comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plasmid_info.remark
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_info.id
     *
     * @return the value of t_plasmid_info.id
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_info.id
     *
     * @param id the value for t_plasmid_info.id
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_info.plasmid_identification
     *
     * @return the value of t_plasmid_info.plasmid_identification
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public String getPlasmid_identification() {
        return plasmid_identification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_info.plasmid_identification
     *
     * @param plasmid_identification the value for t_plasmid_info.plasmid_identification
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public void setPlasmid_identification(String plasmid_identification) {
        this.plasmid_identification = plasmid_identification == null ? null : plasmid_identification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_info.plasmid_name
     *
     * @return the value of t_plasmid_info.plasmid_name
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public String getPlasmid_name() {
        return plasmid_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_info.plasmid_name
     *
     * @param plasmid_name the value for t_plasmid_info.plasmid_name
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public void setPlasmid_name(String plasmid_name) {
        this.plasmid_name = plasmid_name == null ? null : plasmid_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_info.plasmid_name_client
     *
     * @return the value of t_plasmid_info.plasmid_name_client
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public String getPlasmid_name_client() {
        return plasmid_name_client;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_info.plasmid_name_client
     *
     * @param plasmid_name_client the value for t_plasmid_info.plasmid_name_client
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public void setPlasmid_name_client(String plasmid_name_client) {
        this.plasmid_name_client = plasmid_name_client == null ? null : plasmid_name_client.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_info.plasmid_size
     *
     * @return the value of t_plasmid_info.plasmid_size
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public String getPlasmid_size() {
        return plasmid_size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_info.plasmid_size
     *
     * @param plasmid_size the value for t_plasmid_info.plasmid_size
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public void setPlasmid_size(String plasmid_size) {
        this.plasmid_size = plasmid_size == null ? null : plasmid_size.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_info.lab_name
     *
     * @return the value of t_plasmid_info.lab_name
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public String getLab_name() {
        return lab_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_info.lab_name
     *
     * @param lab_name the value for t_plasmid_info.lab_name
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public void setLab_name(String lab_name) {
        this.lab_name = lab_name == null ? null : lab_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_info.plasmid_type
     *
     * @return the value of t_plasmid_info.plasmid_type
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public String getPlasmid_type() {
        return plasmid_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_info.plasmid_type
     *
     * @param plasmid_type the value for t_plasmid_info.plasmid_type
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public void setPlasmid_type(String plasmid_type) {
        this.plasmid_type = plasmid_type == null ? null : plasmid_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_info.plasmid_user_restriction
     *
     * @return the value of t_plasmid_info.plasmid_user_restriction
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public String getPlasmid_user_restriction() {
        return plasmid_user_restriction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_info.plasmid_user_restriction
     *
     * @param plasmid_user_restriction the value for t_plasmid_info.plasmid_user_restriction
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public void setPlasmid_user_restriction(String plasmid_user_restriction) {
        this.plasmid_user_restriction = plasmid_user_restriction == null ? null : plasmid_user_restriction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_info.plasmid_submit_type
     *
     * @return the value of t_plasmid_info.plasmid_submit_type
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public String getPlasmid_submit_type() {
        return plasmid_submit_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_info.plasmid_submit_type
     *
     * @param plasmid_submit_type the value for t_plasmid_info.plasmid_submit_type
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public void setPlasmid_submit_type(String plasmid_submit_type) {
        this.plasmid_submit_type = plasmid_submit_type == null ? null : plasmid_submit_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_info.plasmid_sequence
     *
     * @return the value of t_plasmid_info.plasmid_sequence
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public String getPlasmid_sequence() {
        return plasmid_sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_info.plasmid_sequence
     *
     * @param plasmid_sequence the value for t_plasmid_info.plasmid_sequence
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public void setPlasmid_sequence(String plasmid_sequence) {
        this.plasmid_sequence = plasmid_sequence == null ? null : plasmid_sequence.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_info.plasmid_manufacturer
     *
     * @return the value of t_plasmid_info.plasmid_manufacturer
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public String getPlasmid_manufacturer() {
        return plasmid_manufacturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_info.plasmid_manufacturer
     *
     * @param plasmid_manufacturer the value for t_plasmid_info.plasmid_manufacturer
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public void setPlasmid_manufacturer(String plasmid_manufacturer) {
        this.plasmid_manufacturer = plasmid_manufacturer == null ? null : plasmid_manufacturer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_info.gene_name
     *
     * @return the value of t_plasmid_info.gene_name
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public String getGene_name() {
        return gene_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_info.gene_name
     *
     * @param gene_name the value for t_plasmid_info.gene_name
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public void setGene_name(String gene_name) {
        this.gene_name = gene_name == null ? null : gene_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_info.gene_alias
     *
     * @return the value of t_plasmid_info.gene_alias
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public String getGene_alias() {
        return gene_alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_info.gene_alias
     *
     * @param gene_alias the value for t_plasmid_info.gene_alias
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public void setGene_alias(String gene_alias) {
        this.gene_alias = gene_alias == null ? null : gene_alias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_info.gene_identification
     *
     * @return the value of t_plasmid_info.gene_identification
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public String getGene_identification() {
        return gene_identification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_info.gene_identification
     *
     * @param gene_identification the value for t_plasmid_info.gene_identification
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public void setGene_identification(String gene_identification) {
        this.gene_identification = gene_identification == null ? null : gene_identification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_info.gene_mutation
     *
     * @return the value of t_plasmid_info.gene_mutation
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public String getGene_mutation() {
        return gene_mutation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_info.gene_mutation
     *
     * @param gene_mutation the value for t_plasmid_info.gene_mutation
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public void setGene_mutation(String gene_mutation) {
        this.gene_mutation = gene_mutation == null ? null : gene_mutation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_info.gene_species
     *
     * @return the value of t_plasmid_info.gene_species
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public String getGene_species() {
        return gene_species;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_info.gene_species
     *
     * @param gene_species the value for t_plasmid_info.gene_species
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public void setGene_species(String gene_species) {
        this.gene_species = gene_species == null ? null : gene_species.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_info.gene_size
     *
     * @return the value of t_plasmid_info.gene_size
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public String getGene_size() {
        return gene_size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_info.gene_size
     *
     * @param gene_size the value for t_plasmid_info.gene_size
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public void setGene_size(String gene_size) {
        this.gene_size = gene_size == null ? null : gene_size.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_info.gene_tag
     *
     * @return the value of t_plasmid_info.gene_tag
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public String getGene_tag() {
        return gene_tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_info.gene_tag
     *
     * @param gene_tag the value for t_plasmid_info.gene_tag
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public void setGene_tag(String gene_tag) {
        this.gene_tag = gene_tag == null ? null : gene_tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_info.gene_terminal
     *
     * @return the value of t_plasmid_info.gene_terminal
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public String getGene_terminal() {
        return gene_terminal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_info.gene_terminal
     *
     * @param gene_terminal the value for t_plasmid_info.gene_terminal
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public void setGene_terminal(String gene_terminal) {
        this.gene_terminal = gene_terminal == null ? null : gene_terminal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_info.vector_backbone
     *
     * @return the value of t_plasmid_info.vector_backbone
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public String getVector_backbone() {
        return vector_backbone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_info.vector_backbone
     *
     * @param vector_backbone the value for t_plasmid_info.vector_backbone
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public void setVector_backbone(String vector_backbone) {
        this.vector_backbone = vector_backbone == null ? null : vector_backbone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_info.vector_backbone_manufactor
     *
     * @return the value of t_plasmid_info.vector_backbone_manufactor
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public String getVector_backbone_manufactor() {
        return vector_backbone_manufactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_info.vector_backbone_manufactor
     *
     * @param vector_backbone_manufactor the value for t_plasmid_info.vector_backbone_manufactor
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public void setVector_backbone_manufactor(String vector_backbone_manufactor) {
        this.vector_backbone_manufactor = vector_backbone_manufactor == null ? null : vector_backbone_manufactor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_info.vector_backbone_size
     *
     * @return the value of t_plasmid_info.vector_backbone_size
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public String getVector_backbone_size() {
        return vector_backbone_size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_info.vector_backbone_size
     *
     * @param vector_backbone_size the value for t_plasmid_info.vector_backbone_size
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public void setVector_backbone_size(String vector_backbone_size) {
        this.vector_backbone_size = vector_backbone_size == null ? null : vector_backbone_size.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_info.clone_promoter
     *
     * @return the value of t_plasmid_info.clone_promoter
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public String getClone_promoter() {
        return clone_promoter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_info.clone_promoter
     *
     * @param clone_promoter the value for t_plasmid_info.clone_promoter
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public void setClone_promoter(String clone_promoter) {
        this.clone_promoter = clone_promoter == null ? null : clone_promoter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_info.clone_method
     *
     * @return the value of t_plasmid_info.clone_method
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public String getClone_method() {
        return clone_method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_info.clone_method
     *
     * @param clone_method the value for t_plasmid_info.clone_method
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public void setClone_method(String clone_method) {
        this.clone_method = clone_method == null ? null : clone_method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_info.clone_site
     *
     * @return the value of t_plasmid_info.clone_site
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public String getClone_site() {
        return clone_site;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_info.clone_site
     *
     * @param clone_site the value for t_plasmid_info.clone_site
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public void setClone_site(String clone_site) {
        this.clone_site = clone_site == null ? null : clone_site.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_info.clone_sequence_primer
     *
     * @return the value of t_plasmid_info.clone_sequence_primer
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public String getClone_sequence_primer() {
        return clone_sequence_primer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_info.clone_sequence_primer
     *
     * @param clone_sequence_primer the value for t_plasmid_info.clone_sequence_primer
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public void setClone_sequence_primer(String clone_sequence_primer) {
        this.clone_sequence_primer = clone_sequence_primer == null ? null : clone_sequence_primer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_info.clone_sequence_primer_reverse
     *
     * @return the value of t_plasmid_info.clone_sequence_primer_reverse
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public String getClone_sequence_primer_reverse() {
        return clone_sequence_primer_reverse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_info.clone_sequence_primer_reverse
     *
     * @param clone_sequence_primer_reverse the value for t_plasmid_info.clone_sequence_primer_reverse
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public void setClone_sequence_primer_reverse(String clone_sequence_primer_reverse) {
        this.clone_sequence_primer_reverse = clone_sequence_primer_reverse == null ? null : clone_sequence_primer_reverse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_info.growth_bacterial_resistance
     *
     * @return the value of t_plasmid_info.growth_bacterial_resistance
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public String getGrowth_bacterial_resistance() {
        return growth_bacterial_resistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_info.growth_bacterial_resistance
     *
     * @param growth_bacterial_resistance the value for t_plasmid_info.growth_bacterial_resistance
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public void setGrowth_bacterial_resistance(String growth_bacterial_resistance) {
        this.growth_bacterial_resistance = growth_bacterial_resistance == null ? null : growth_bacterial_resistance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_info.growth_strain
     *
     * @return the value of t_plasmid_info.growth_strain
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public String getGrowth_strain() {
        return growth_strain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_info.growth_strain
     *
     * @param growth_strain the value for t_plasmid_info.growth_strain
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public void setGrowth_strain(String growth_strain) {
        this.growth_strain = growth_strain == null ? null : growth_strain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_info.growth_copy_number
     *
     * @return the value of t_plasmid_info.growth_copy_number
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public String getGrowth_copy_number() {
        return growth_copy_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_info.growth_copy_number
     *
     * @param growth_copy_number the value for t_plasmid_info.growth_copy_number
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public void setGrowth_copy_number(String growth_copy_number) {
        this.growth_copy_number = growth_copy_number == null ? null : growth_copy_number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_info.growth_temperature
     *
     * @return the value of t_plasmid_info.growth_temperature
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public String getGrowth_temperature() {
        return growth_temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_info.growth_temperature
     *
     * @param growth_temperature the value for t_plasmid_info.growth_temperature
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public void setGrowth_temperature(String growth_temperature) {
        this.growth_temperature = growth_temperature == null ? null : growth_temperature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_info.growth_selection_mark
     *
     * @return the value of t_plasmid_info.growth_selection_mark
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public String getGrowth_selection_mark() {
        return growth_selection_mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_info.growth_selection_mark
     *
     * @param growth_selection_mark the value for t_plasmid_info.growth_selection_mark
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public void setGrowth_selection_mark(String growth_selection_mark) {
        this.growth_selection_mark = growth_selection_mark == null ? null : growth_selection_mark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_info.sequence_part_one
     *
     * @return the value of t_plasmid_info.sequence_part_one
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public String getSequence_part_one() {
        return sequence_part_one;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_info.sequence_part_one
     *
     * @param sequence_part_one the value for t_plasmid_info.sequence_part_one
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public void setSequence_part_one(String sequence_part_one) {
        this.sequence_part_one = sequence_part_one == null ? null : sequence_part_one.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_info.sequence_part_one_description
     *
     * @return the value of t_plasmid_info.sequence_part_one_description
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public String getSequence_part_one_description() {
        return sequence_part_one_description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_info.sequence_part_one_description
     *
     * @param sequence_part_one_description the value for t_plasmid_info.sequence_part_one_description
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public void setSequence_part_one_description(String sequence_part_one_description) {
        this.sequence_part_one_description = sequence_part_one_description == null ? null : sequence_part_one_description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_info.sequence_part_two
     *
     * @return the value of t_plasmid_info.sequence_part_two
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public String getSequence_part_two() {
        return sequence_part_two;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_info.sequence_part_two
     *
     * @param sequence_part_two the value for t_plasmid_info.sequence_part_two
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public void setSequence_part_two(String sequence_part_two) {
        this.sequence_part_two = sequence_part_two == null ? null : sequence_part_two.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_info.sequence_part_two_description
     *
     * @return the value of t_plasmid_info.sequence_part_two_description
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public String getSequence_part_two_description() {
        return sequence_part_two_description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_info.sequence_part_two_description
     *
     * @param sequence_part_two_description the value for t_plasmid_info.sequence_part_two_description
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public void setSequence_part_two_description(String sequence_part_two_description) {
        this.sequence_part_two_description = sequence_part_two_description == null ? null : sequence_part_two_description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_info.att_urls
     *
     * @return the value of t_plasmid_info.att_urls
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public String getAtt_urls() {
        return att_urls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_info.att_urls
     *
     * @param att_urls the value for t_plasmid_info.att_urls
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public void setAtt_urls(String att_urls) {
        this.att_urls = att_urls == null ? null : att_urls.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_info.vector_modifications
     *
     * @return the value of t_plasmid_info.vector_modifications
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public String getVector_modifications() {
        return vector_modifications;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_info.vector_modifications
     *
     * @param vector_modifications the value for t_plasmid_info.vector_modifications
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public void setVector_modifications(String vector_modifications) {
        this.vector_modifications = vector_modifications == null ? null : vector_modifications.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_info.gene_link
     *
     * @return the value of t_plasmid_info.gene_link
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public String getGene_link() {
        return gene_link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_info.gene_link
     *
     * @param gene_link the value for t_plasmid_info.gene_link
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public void setGene_link(String gene_link) {
        this.gene_link = gene_link == null ? null : gene_link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_info.add_time
     *
     * @return the value of t_plasmid_info.add_time
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public Date getAdd_time() {
        return add_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_info.add_time
     *
     * @param add_time the value for t_plasmid_info.add_time
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public void setAdd_time(Date add_time) {
        this.add_time = add_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_info.source_article
     *
     * @return the value of t_plasmid_info.source_article
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public String getSource_article() {
        return source_article;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_info.source_article
     *
     * @param source_article the value for t_plasmid_info.source_article
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public void setSource_article(String source_article) {
        this.source_article = source_article == null ? null : source_article.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_info.plasmid_description
     *
     * @return the value of t_plasmid_info.plasmid_description
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public String getPlasmid_description() {
        return plasmid_description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_info.plasmid_description
     *
     * @param plasmid_description the value for t_plasmid_info.plasmid_description
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public void setPlasmid_description(String plasmid_description) {
        this.plasmid_description = plasmid_description == null ? null : plasmid_description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_info.gene_description
     *
     * @return the value of t_plasmid_info.gene_description
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public String getGene_description() {
        return gene_description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_info.gene_description
     *
     * @param gene_description the value for t_plasmid_info.gene_description
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public void setGene_description(String gene_description) {
        this.gene_description = gene_description == null ? null : gene_description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_info.vector_type
     *
     * @return the value of t_plasmid_info.vector_type
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public String getVector_type() {
        return vector_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_info.vector_type
     *
     * @param vector_type the value for t_plasmid_info.vector_type
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public void setVector_type(String vector_type) {
        this.vector_type = vector_type == null ? null : vector_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_info.growth_comment
     *
     * @return the value of t_plasmid_info.growth_comment
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public String getGrowth_comment() {
        return growth_comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_info.growth_comment
     *
     * @param growth_comment the value for t_plasmid_info.growth_comment
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public void setGrowth_comment(String growth_comment) {
        this.growth_comment = growth_comment == null ? null : growth_comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plasmid_info.remark
     *
     * @return the value of t_plasmid_info.remark
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plasmid_info.remark
     *
     * @param remark the value for t_plasmid_info.remark
     *
     * @mbg.generated Fri Aug 21 19:52:31 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}