package com.genetech.bean;

import java.util.Date;

public class SiteUser {
    public SiteUser() {
    }

    public SiteUser(Integer id, String loginName, String userName, String password, String email, String telephone, Date lastLoginTime, Date createdTime, Date modifiedTime, Integer roleId, Integer orderId, String userSource, Integer isActive, String remark, String institute, String area, String lab_leader, Integer organization_type, String pi_name, String pi_phone, String real_name, String institute_address) {
        this.id = id;
        this.loginName = loginName;
        this.userName = userName;
        this.password = password;
        this.email = email;
        this.telephone = telephone;
        this.lastLoginTime = lastLoginTime;
        this.createdTime = createdTime;
        this.modifiedTime = modifiedTime;
        this.roleId = roleId;
        this.orderId = orderId;
        this.userSource = userSource;
        this.isActive = isActive;
        this.remark = remark;
        this.institute = institute;
        this.area = area;
        this.lab_leader = lab_leader;
        this.organization_type = organization_type;
        this.pi_name = pi_name;
        this.pi_phone = pi_phone;
        this.real_name = real_name;
        this.institute_address = institute_address;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_site_user.id
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_site_user.loginName
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_site_user.userName
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_site_user.password
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_site_user.email
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_site_user.telephone
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_site_user.lastLoginTime
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    private Date lastLoginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_site_user.createdTime
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_site_user.modifiedTime
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    private Date modifiedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_site_user.roleId
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_site_user.orderId
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_site_user.userSource
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    private String userSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_site_user.isActive
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    private Integer isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_site_user.remark
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_site_user.institute
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    private String institute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_site_user.area
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_site_user.lab_leader
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    private String lab_leader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_site_user.organization_type
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    private Integer organization_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_site_user.pi_name
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    private String pi_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_site_user.pi_phone
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    private String pi_phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_site_user.real_name
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    private String real_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_site_user.institute_address
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    private String institute_address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_site_user.id
     *
     * @return the value of t_site_user.id
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_site_user.id
     *
     * @param id the value for t_site_user.id
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_site_user.loginName
     *
     * @return the value of t_site_user.loginName
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_site_user.loginName
     *
     * @param loginName the value for t_site_user.loginName
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_site_user.userName
     *
     * @return the value of t_site_user.userName
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_site_user.userName
     *
     * @param userName the value for t_site_user.userName
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_site_user.password
     *
     * @return the value of t_site_user.password
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_site_user.password
     *
     * @param password the value for t_site_user.password
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_site_user.email
     *
     * @return the value of t_site_user.email
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_site_user.email
     *
     * @param email the value for t_site_user.email
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_site_user.telephone
     *
     * @return the value of t_site_user.telephone
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_site_user.telephone
     *
     * @param telephone the value for t_site_user.telephone
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_site_user.lastLoginTime
     *
     * @return the value of t_site_user.lastLoginTime
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_site_user.lastLoginTime
     *
     * @param lastLoginTime the value for t_site_user.lastLoginTime
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_site_user.createdTime
     *
     * @return the value of t_site_user.createdTime
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_site_user.createdTime
     *
     * @param createdTime the value for t_site_user.createdTime
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_site_user.modifiedTime
     *
     * @return the value of t_site_user.modifiedTime
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_site_user.modifiedTime
     *
     * @param modifiedTime the value for t_site_user.modifiedTime
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_site_user.roleId
     *
     * @return the value of t_site_user.roleId
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_site_user.roleId
     *
     * @param roleId the value for t_site_user.roleId
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_site_user.orderId
     *
     * @return the value of t_site_user.orderId
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_site_user.orderId
     *
     * @param orderId the value for t_site_user.orderId
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_site_user.userSource
     *
     * @return the value of t_site_user.userSource
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    public String getUserSource() {
        return userSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_site_user.userSource
     *
     * @param userSource the value for t_site_user.userSource
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    public void setUserSource(String userSource) {
        this.userSource = userSource == null ? null : userSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_site_user.isActive
     *
     * @return the value of t_site_user.isActive
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    public Integer getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_site_user.isActive
     *
     * @param isActive the value for t_site_user.isActive
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    public void setIsActive(Integer isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_site_user.remark
     *
     * @return the value of t_site_user.remark
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_site_user.remark
     *
     * @param remark the value for t_site_user.remark
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_site_user.institute
     *
     * @return the value of t_site_user.institute
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    public String getInstitute() {
        return institute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_site_user.institute
     *
     * @param institute the value for t_site_user.institute
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    public void setInstitute(String institute) {
        this.institute = institute == null ? null : institute.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_site_user.area
     *
     * @return the value of t_site_user.area
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_site_user.area
     *
     * @param area the value for t_site_user.area
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_site_user.lab_leader
     *
     * @return the value of t_site_user.lab_leader
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    public String getLab_leader() {
        return lab_leader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_site_user.lab_leader
     *
     * @param lab_leader the value for t_site_user.lab_leader
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    public void setLab_leader(String lab_leader) {
        this.lab_leader = lab_leader == null ? null : lab_leader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_site_user.organization_type
     *
     * @return the value of t_site_user.organization_type
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    public Integer getOrganization_type() {
        return organization_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_site_user.organization_type
     *
     * @param organization_type the value for t_site_user.organization_type
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    public void setOrganization_type(Integer organization_type) {
        this.organization_type = organization_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_site_user.pi_name
     *
     * @return the value of t_site_user.pi_name
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    public String getPi_name() {
        return pi_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_site_user.pi_name
     *
     * @param pi_name the value for t_site_user.pi_name
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    public void setPi_name(String pi_name) {
        this.pi_name = pi_name == null ? null : pi_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_site_user.pi_phone
     *
     * @return the value of t_site_user.pi_phone
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    public String getPi_phone() {
        return pi_phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_site_user.pi_phone
     *
     * @param pi_phone the value for t_site_user.pi_phone
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    public void setPi_phone(String pi_phone) {
        this.pi_phone = pi_phone == null ? null : pi_phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_site_user.real_name
     *
     * @return the value of t_site_user.real_name
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    public String getReal_name() {
        return real_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_site_user.real_name
     *
     * @param real_name the value for t_site_user.real_name
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    public void setReal_name(String real_name) {
        this.real_name = real_name == null ? null : real_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_site_user.institute_address
     *
     * @return the value of t_site_user.institute_address
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    public String getInstitute_address() {
        return institute_address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_site_user.institute_address
     *
     * @param institute_address the value for t_site_user.institute_address
     *
     * @mbg.generated Fri Dec 27 15:21:11 CST 2019
     */
    public void setInstitute_address(String institute_address) {
        this.institute_address = institute_address == null ? null : institute_address.trim();
    }
}