package com.genetech.dao;

import com.genetech.bean.DeliveryAddress;
import com.genetech.bean.DeliveryAddressExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface DeliveryAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_delivery_address
     *
     * @mbg.generated Fri Dec 27 15:23:01 CST 2019
     */
    long countByExample(DeliveryAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_delivery_address
     *
     * @mbg.generated Fri Dec 27 15:23:01 CST 2019
     */
    int deleteByExample(DeliveryAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_delivery_address
     *
     * @mbg.generated Fri Dec 27 15:23:01 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_delivery_address
     *
     * @mbg.generated Fri Dec 27 15:23:01 CST 2019
     */
    int insert(DeliveryAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_delivery_address
     *
     * @mbg.generated Fri Dec 27 15:23:01 CST 2019
     */
    int insertSelective(DeliveryAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_delivery_address
     *
     * @mbg.generated Fri Dec 27 15:23:01 CST 2019
     */
    List<DeliveryAddress> selectByExample(DeliveryAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_delivery_address
     *
     * @mbg.generated Fri Dec 27 15:23:01 CST 2019
     */
    DeliveryAddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_delivery_address
     *
     * @mbg.generated Fri Dec 27 15:23:01 CST 2019
     */
    int updateByExampleSelective(@Param("record") DeliveryAddress record, @Param("example") DeliveryAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_delivery_address
     *
     * @mbg.generated Fri Dec 27 15:23:01 CST 2019
     */
    int updateByExample(@Param("record") DeliveryAddress record, @Param("example") DeliveryAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_delivery_address
     *
     * @mbg.generated Fri Dec 27 15:23:01 CST 2019
     */
    int updateByPrimaryKeySelective(DeliveryAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_delivery_address
     *
     * @mbg.generated Fri Dec 27 15:23:01 CST 2019
     */
    int updateByPrimaryKey(DeliveryAddress record);
}