package com.genetech.dao;

import com.genetech.bean.PlasmidDict;
import com.genetech.bean.PlasmidDictExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PlasmidDictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plasmid_dict
     *
     * @mbg.generated Sun Dec 29 15:10:25 CST 2019
     */
    long countByExample(PlasmidDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plasmid_dict
     *
     * @mbg.generated Sun Dec 29 15:10:25 CST 2019
     */
    int deleteByExample(PlasmidDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plasmid_dict
     *
     * @mbg.generated Sun Dec 29 15:10:25 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plasmid_dict
     *
     * @mbg.generated Sun Dec 29 15:10:25 CST 2019
     */
    int insert(PlasmidDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plasmid_dict
     *
     * @mbg.generated Sun Dec 29 15:10:25 CST 2019
     */
    int insertSelective(PlasmidDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plasmid_dict
     *
     * @mbg.generated Sun Dec 29 15:10:25 CST 2019
     */
    List<PlasmidDict> selectByExample(PlasmidDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plasmid_dict
     *
     * @mbg.generated Sun Dec 29 15:10:25 CST 2019
     */
    PlasmidDict selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plasmid_dict
     *
     * @mbg.generated Sun Dec 29 15:10:25 CST 2019
     */
    int updateByExampleSelective(@Param("record") PlasmidDict record, @Param("example") PlasmidDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plasmid_dict
     *
     * @mbg.generated Sun Dec 29 15:10:25 CST 2019
     */
    int updateByExample(@Param("record") PlasmidDict record, @Param("example") PlasmidDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plasmid_dict
     *
     * @mbg.generated Sun Dec 29 15:10:25 CST 2019
     */
    int updateByPrimaryKeySelective(PlasmidDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plasmid_dict
     *
     * @mbg.generated Sun Dec 29 15:10:25 CST 2019
     */
    int updateByPrimaryKey(PlasmidDict record);

    List<String> selectPlasmidDictByColumn( @Param("columnName")String columnName);
}