package com.genetech.dao;

import com.genetech.bean.PlasmidInfo;
import com.genetech.bean.PlasmidInfoExample;
import java.util.List;

import com.genetech.bean.dto.PlasmidInfoDto;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface PlasmidInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plasmid_info
     *
     * @mbg.generated Thu Feb 27 22:16:01 CST 2020
     */
    long countByExample(PlasmidInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plasmid_info
     *
     * @mbg.generated Thu Feb 27 22:16:01 CST 2020
     */
    int deleteByExample(PlasmidInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plasmid_info
     *
     * @mbg.generated Thu Feb 27 22:16:01 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plasmid_info
     *
     * @mbg.generated Thu Feb 27 22:16:01 CST 2020
     */
    int insert(PlasmidInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plasmid_info
     *
     * @mbg.generated Thu Feb 27 22:16:01 CST 2020
     */
    int insertSelective(PlasmidInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plasmid_info
     *
     * @mbg.generated Thu Feb 27 22:16:01 CST 2020
     */
    List<PlasmidInfo> selectByExampleWithBLOBs(PlasmidInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plasmid_info
     *
     * @mbg.generated Thu Feb 27 22:16:01 CST 2020
     */
    List<PlasmidInfo> selectByExample(PlasmidInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plasmid_info
     *
     * @mbg.generated Thu Feb 27 22:16:01 CST 2020
     */
    PlasmidInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plasmid_info
     *
     * @mbg.generated Thu Feb 27 22:16:01 CST 2020
     */
    int updateByExampleSelective(@Param("record") PlasmidInfo record, @Param("example") PlasmidInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plasmid_info
     *
     * @mbg.generated Thu Feb 27 22:16:01 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") PlasmidInfo record, @Param("example") PlasmidInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plasmid_info
     *
     * @mbg.generated Thu Feb 27 22:16:01 CST 2020
     */
    int updateByExample(@Param("record") PlasmidInfo record, @Param("example") PlasmidInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plasmid_info
     *
     * @mbg.generated Thu Feb 27 22:16:01 CST 2020
     */
    int updateByPrimaryKeySelective(PlasmidInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plasmid_info
     *
     * @mbg.generated Thu Feb 27 22:16:01 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(PlasmidInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plasmid_info
     *
     * @mbg.generated Thu Feb 27 22:16:01 CST 2020
     */
    int updateByPrimaryKey(PlasmidInfo record);

    List<PlasmidInfo> searchPlasmidInfos(PlasmidInfoDto plasmidInfoDto);
}